// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: orders/order.proto
// Protobuf C++ Version: 7.35.1

#include "orders/order.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::myapp::Order_Item
        {&::_pbi::kDescriptorMethods, &::descriptor_table_orders_2forder_2eproto, /* tracker*/ nullptr,},
        // ::myapp::Order_MetadataEntry_DoNotUse
        {&::_pbi::kDescriptorMethods, &::descriptor_table_orders_2forder_2eproto, /* tracker*/ nullptr,},
        // ::myapp::Order
        {&::_pbi::kDescriptorMethods, &::descriptor_table_orders_2forder_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
namespace myapp {
constexpr Order_MetadataEntry_DoNotUse::ParseTableT_ Order_MetadataEntry_DoNotUse::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(Order_MetadataEntry_DoNotUse, _impl_._has_bits_),
      0, // no _extensions_
      2, 8,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967292,  // skipmap
      offsetof(ParseTableT_, field_entries),
      2,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::myapp::Order_MetadataEntry_DoNotUse>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // string value = 2;
      {::_pbi::TcParser::FastUS1,
       {18, 1, 0,
        PROTOBUF_FIELD_OFFSET(Order_MetadataEntry_DoNotUse, _impl_.value_)}},
      // string key = 1;
      {::_pbi::TcParser::FastUS1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(Order_MetadataEntry_DoNotUse, _impl_.key_)}},
    }}, {{
      65535, 65535
    }}, {{
      // string key = 1;
      {PROTOBUF_FIELD_OFFSET(Order_MetadataEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // string value = 2;
      {PROTOBUF_FIELD_OFFSET(Order_MetadataEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    }},
    // no aux_entries
    {{
      "\31\3\5\0\0\0\0\0"
      "myapp.Order.MetadataEntry"
      "key"
      "value"
    }},
  };
}

template <typename>
constexpr Order_MetadataEntry_DoNotUse::Order_MetadataEntry_DoNotUse(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Order_MetadataEntry_DoNotUse::MapEntry(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
      ) {
}
inline void* PROTOBUF_NONNULL Order_MetadataEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Order_MetadataEntry_DoNotUse(arena);
}
constexpr auto Order_MetadataEntry_DoNotUse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Order_MetadataEntry_DoNotUse), alignof(Order_MetadataEntry_DoNotUse));
}
constexpr auto Order_MetadataEntry_DoNotUse::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &Order_MetadataEntry_DoNotUse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Order_MetadataEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Order_MetadataEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&Order_MetadataEntry_DoNotUse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Order_MetadataEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[1],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_orders_2forder_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct Order_MetadataEntry_DoNotUseGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr Order_MetadataEntry_DoNotUseGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 Order_MetadataEntry_DoNotUse_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(Order_MetadataEntry_DoNotUse::InternalGenerateClassData_(
            _default, &Order_MetadataEntry_DoNotUse_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<Order_MetadataEntry_DoNotUse>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~Order_MetadataEntry_DoNotUseGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) Order_MetadataEntry_DoNotUse _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<Order_MetadataEntry_DoNotUse>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(Order_MetadataEntry_DoNotUseGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST Order_MetadataEntry_DoNotUseGlobalsTypeInternal Order_MetadataEntry_DoNotUse_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* Order_MetadataEntry_DoNotUse_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return Order_MetadataEntry_DoNotUse_globals_.GetClassData();
#else
  return Order_MetadataEntry_DoNotUse_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class Order_Item::_Internal {
 public:
  using HasBits = decltype(::std::declval<Order_Item>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Order_Item, _impl_._has_bits_);
};

constexpr Order_Item::ParseTableT_ Order_Item::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(Order_Item, _impl_._has_bits_),
      0, // no _extensions_
      4, 24,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967280,  // skipmap
      offsetof(ParseTableT_, field_entries),
      4,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::myapp::Order_Item>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // double unit_price = 4;
      {::_pbi::TcParser::FastF64S1,
       {33, 2, 0,
        PROTOBUF_FIELD_OFFSET(Order_Item, _impl_.unit_price_)}},
      // string sku = 1;
      {::_pbi::TcParser::FastUS1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(Order_Item, _impl_.sku_)}},
      // string title = 2;
      {::_pbi::TcParser::FastUS1,
       {18, 1, 0,
        PROTOBUF_FIELD_OFFSET(Order_Item, _impl_.title_)}},
      // int32 quantity = 3;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Order_Item, _impl_.quantity_), 3>(),
       {24, 3, 0,
        PROTOBUF_FIELD_OFFSET(Order_Item, _impl_.quantity_)}},
    }}, {{
      65535, 65535
    }}, {{
      // string sku = 1;
      {PROTOBUF_FIELD_OFFSET(Order_Item, _impl_.sku_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // string title = 2;
      {PROTOBUF_FIELD_OFFSET(Order_Item, _impl_.title_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // int32 quantity = 3;
      {PROTOBUF_FIELD_OFFSET(Order_Item, _impl_.quantity_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
      // double unit_price = 4;
      {PROTOBUF_FIELD_OFFSET(Order_Item, _impl_.unit_price_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    }},
    // no aux_entries
    {{
      "\20\3\5\0\0\0\0\0"
      "myapp.Order.Item"
      "sku"
      "title"
    }},
  };
}


inline constexpr Order_Item::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        sku_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        title_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        unit_price_{0},
        quantity_{0} {}

template <typename>
constexpr Order_Item::Order_Item(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL Order_Item::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Order_Item(arena);
}
constexpr auto Order_Item::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Order_Item), alignof(Order_Item));
}
constexpr auto Order_Item::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &Order_Item::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Order_Item>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Order_Item::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Order_Item>(), &Order_Item::ByteSizeLong,
              &Order_Item::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Order_Item, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_orders_2forder_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct Order_ItemGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr Order_ItemGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 Order_Item_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(Order_Item::InternalGenerateClassData_(
            _default, &Order_Item_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<Order_Item>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~Order_ItemGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) Order_Item _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<Order_Item>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(Order_ItemGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST Order_ItemGlobalsTypeInternal Order_Item_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* Order_Item_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return Order_Item_globals_.GetClassData();
#else
  return Order_Item_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class Order::_Internal {
 public:
  using HasBits = decltype(::std::declval<Order>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Order, _impl_._has_bits_);
};

constexpr Order::ParseTableT_ Order::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(Order, _impl_._has_bits_),
      0, // no _extensions_
      8, 56,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967040,  // skipmap
      offsetof(ParseTableT_, field_entries),
      8,  // num_field_entries
      4,  // num_aux_entries
      offsetof(ParseTableT_, aux_entries),
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::myapp::Order>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // optional string tracking_number = 8;
      {::_pbi::TcParser::FastUS1,
       {66, 1, 0,
        PROTOBUF_FIELD_OFFSET(Order, _impl_.tracking_number_)}},
      // int64 order_id = 1;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Order, _impl_.order_id_), 4>(),
       {8, 4, 0,
        PROTOBUF_FIELD_OFFSET(Order, _impl_.order_id_)}},
      // .myapp.User buyer = 2;
      {::_pbi::TcParser::FastMtS1,
       {18, 2, 0,
        PROTOBUF_FIELD_OFFSET(Order, _impl_.buyer_)}},
      // .myapp.Address shipping_address = 3;
      {::_pbi::TcParser::FastMtS1,
       {26, 3, 1,
        PROTOBUF_FIELD_OFFSET(Order, _impl_.shipping_address_)}},
      // repeated .myapp.Order.Item item = 4;
      {::_pbi::TcParser::FastMtR1,
       {34, 0, 2,
        PROTOBUF_FIELD_OFFSET(Order, _impl_.item_)}},
      // .myapp.Order.OrderStatus status = 5;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Order, _impl_.status_), 6>(),
       {40, 6, 0,
        PROTOBUF_FIELD_OFFSET(Order, _impl_.status_)}},
      // double total_amount = 6;
      {::_pbi::TcParser::FastF64S1,
       {49, 5, 0,
        PROTOBUF_FIELD_OFFSET(Order, _impl_.total_amount_)}},
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, {{
      // int64 order_id = 1;
      {PROTOBUF_FIELD_OFFSET(Order, _impl_.order_id_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
      // .myapp.User buyer = 2;
      {PROTOBUF_FIELD_OFFSET(Order, _impl_.buyer_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
      // .myapp.Address shipping_address = 3;
      {PROTOBUF_FIELD_OFFSET(Order, _impl_.shipping_address_), _Internal::kHasBitsOffset + 3, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
      // repeated .myapp.Order.Item item = 4;
      {PROTOBUF_FIELD_OFFSET(Order, _impl_.item_), _Internal::kHasBitsOffset + 0, 2, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
      // .myapp.Order.OrderStatus status = 5;
      {PROTOBUF_FIELD_OFFSET(Order, _impl_.status_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
      // double total_amount = 6;
      {PROTOBUF_FIELD_OFFSET(Order, _impl_.total_amount_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
      // map<string, string> metadata = 7;
      {PROTOBUF_FIELD_OFFSET(Order, _impl_.metadata_), _Internal::kHasBitsOffset + 7, 3, (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
      // optional string tracking_number = 8;
      {PROTOBUF_FIELD_OFFSET(Order, _impl_.tracking_number_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    }},
    {{
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::myapp::User>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::myapp::User_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::myapp::Address>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::myapp::Address_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::myapp::Order_Item>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::myapp::Order_Item_globals_},
        #endif
        {::_pbi::TcParser::GetMapAuxInfo(
            1, 0, 9, 9, 0)},
    }},
    {{
      "\13\0\0\0\0\0\0\10\17\0\0\0\0\0\0\0"
      "myapp.Order"
      "metadata"
      "tracking_number"
    }},
  };
}


inline constexpr Order::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        item_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::myapp::Order,
            PROTOBUF_FIELD_OFFSET(::myapp::Order, _impl_.item_)>()
         }
        ,
        tracking_number_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        buyer_{nullptr},
        shipping_address_{nullptr},
        order_id_{::int64_t{0}},
        total_amount_{0},
        status_{static_cast< ::myapp::Order_OrderStatus >(0)},
        metadata_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::myapp::Order,
            PROTOBUF_FIELD_OFFSET(::myapp::Order, _impl_.metadata_)>()
         }
     {}

template <typename>
constexpr Order::Order(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL Order::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Order(arena);
}
constexpr auto Order::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Order), alignof(Order));
}
constexpr auto Order::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &Order::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Order>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Order::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Order>(), &Order::ByteSizeLong,
              &Order::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Order, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[2],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_orders_2forder_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct OrderGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr OrderGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 Order_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(Order::InternalGenerateClassData_(
            _default, &Order_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<Order>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~OrderGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) Order _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<Order>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(OrderGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST OrderGlobalsTypeInternal Order_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* Order_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return Order_globals_.GetClassData();
#else
  return Order_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace myapp
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_orders_2forder_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_orders_2forder_2eproto = nullptr;
const ::uint32_t
    TableStruct_orders_2forder_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::myapp::Order_Item, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::myapp::Order_Item, _impl_.sku_),
        PROTOBUF_FIELD_OFFSET(::myapp::Order_Item, _impl_.title_),
        PROTOBUF_FIELD_OFFSET(::myapp::Order_Item, _impl_.quantity_),
        PROTOBUF_FIELD_OFFSET(::myapp::Order_Item, _impl_.unit_price_),
        0,
        1,
        3,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::myapp::Order_MetadataEntry_DoNotUse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::myapp::Order_MetadataEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::myapp::Order_MetadataEntry_DoNotUse, _impl_.value_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::myapp::Order, _impl_._has_bits_),
        11, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::myapp::Order, _impl_.order_id_),
        PROTOBUF_FIELD_OFFSET(::myapp::Order, _impl_.buyer_),
        PROTOBUF_FIELD_OFFSET(::myapp::Order, _impl_.shipping_address_),
        PROTOBUF_FIELD_OFFSET(::myapp::Order, _impl_.item_),
        PROTOBUF_FIELD_OFFSET(::myapp::Order, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::myapp::Order, _impl_.total_amount_),
        PROTOBUF_FIELD_OFFSET(::myapp::Order, _impl_.metadata_),
        PROTOBUF_FIELD_OFFSET(::myapp::Order, _impl_.tracking_number_),
        4,
        2,
        3,
        0,
        6,
        5,
        7,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::myapp::Order_Item)},
        {11, sizeof(::myapp::Order_MetadataEntry_DoNotUse)},
        {18, sizeof(::myapp::Order)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::myapp::Order_Item_globals_,
        &::myapp::Order_MetadataEntry_DoNotUse_globals_,
        &::myapp::Order_globals_,
};
const char descriptor_table_protodef_orders_2forder_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022orders/order.proto\022\005myapp\032\020users/user."
    "proto\032\024common/address.proto\"\254\004\n\005Order\022\020\n"
    "\010order_id\030\001 \001(\003\022\032\n\005buyer\030\002 \001(\0132\013.myapp.U"
    "ser\022(\n\020shipping_address\030\003 \001(\0132\016.myapp.Ad"
    "dress\022\037\n\004item\030\004 \003(\0132\021.myapp.Order.Item\022("
    "\n\006status\030\005 \001(\0162\030.myapp.Order.OrderStatus"
    "\022\024\n\014total_amount\030\006 \001(\001\022,\n\010metadata\030\007 \003(\013"
    "2\032.myapp.Order.MetadataEntry\022\034\n\017tracking"
    "_number\030\010 \001(\tH\000\210\001\001\032H\n\004Item\022\013\n\003sku\030\001 \001(\t\022"
    "\r\n\005title\030\002 \001(\t\022\020\n\010quantity\030\003 \001(\005\022\022\n\nunit"
    "_price\030\004 \001(\001\032/\n\rMetadataEntry\022\013\n\003key\030\001 \001"
    "(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\216\001\n\013OrderStatus\022\030\n"
    "\024ORDER_STATUS_UNKNOWN\020\000\022\030\n\024ORDER_STATUS_"
    "PENDING\020\001\022\025\n\021ORDER_STATUS_PAID\020\002\022\030\n\024ORDE"
    "R_STATUS_SHIPPED\020\003\022\032\n\026ORDER_STATUS_CANCE"
    "LLED\020\004B\022\n\020_tracking_numberB\002H\001b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_orders_2forder_2eproto_deps[2] = {
        &::descriptor_table_common_2faddress_2eproto,
        &::descriptor_table_users_2fuser_2eproto,
};
static ::absl::once_flag descriptor_table_orders_2forder_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_orders_2forder_2eproto = {
    false,
    false,
    638,
    descriptor_table_protodef_orders_2forder_2eproto,
    "orders/order.proto",
    &descriptor_table_orders_2forder_2eproto_once,
    descriptor_table_orders_2forder_2eproto_deps,
    2,
    3,
    schemas,
    file_message_globals,
    TableStruct_orders_2forder_2eproto::offsets,
    file_level_enum_descriptors_orders_2forder_2eproto,
    file_level_service_descriptors_orders_2forder_2eproto,
};
namespace myapp {
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
Order_OrderStatus_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_orders_2forder_2eproto);
  return file_level_enum_descriptors_orders_2forder_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Order_OrderStatus_internal_data_[] = {
    327680u, 0u, };
// ===================================================================

Order_Item::Order_Item(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Order_Item_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:myapp.Order.Item)
}
PROTOBUF_NDEBUG_INLINE Order_Item::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::myapp::Order_Item& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        sku_(arena, from.sku_),
        title_(arena, from.title_) {}

Order_Item::Order_Item(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Order_Item& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Order_Item_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Order_Item* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, unit_price_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, unit_price_),
           offsetof(Impl_, quantity_) -
               offsetof(Impl_, unit_price_) +
               sizeof(Impl_::quantity_));

  // @@protoc_insertion_point(copy_constructor:myapp.Order.Item)
}
PROTOBUF_NDEBUG_INLINE Order_Item::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        sku_(arena),
        title_(arena) {}

inline void Order_Item::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, unit_price_),
           0,
           offsetof(Impl_, quantity_) -
               offsetof(Impl_, unit_price_) +
               sizeof(Impl_::quantity_));
}
Order_Item::~Order_Item() {
  // @@protoc_insertion_point(destructor:myapp.Order.Item)
  SharedDtor(*this);
}
inline void Order_Item::SharedDtor(MessageLite& self) {
  Order_Item& this_ = static_cast<Order_Item&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.sku_.Destroy();
  this_._impl_.title_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Order_Item_class_data_ =
        Order_Item::InternalGenerateClassData_(Order_Item_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Order_Item::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Order_Item_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Order_Item_class_data_.tc_table);
  return Order_Item_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Order_Item::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Order_Item_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&Order_Item_globals_));
  return Order_Item_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const Order_Item::ParseTableT_
    Order_Item::_table_ =
        Order_Item::InternalGenerateParseTable_(Order_Item_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void Order_Item::Clear() {
// @@protoc_insertion_point(message_clear_start:myapp.Order.Item)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.sku_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.title_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000000cU)) {
    ::memset(&_impl_.unit_price_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.quantity_) -
        reinterpret_cast<char*>(&_impl_.unit_price_)) + sizeof(_impl_.quantity_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Order_Item::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Order_Item& this_ = static_cast<const Order_Item&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Order_Item::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Order_Item& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:myapp.Order.Item)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string sku = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_sku().empty()) {
      const ::std::string& _s = this_._internal_sku();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "myapp.Order.Item.sku");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string title = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_title().empty()) {
      const ::std::string& _s = this_._internal_title();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "myapp.Order.Item.title");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // int32 quantity = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_quantity() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_quantity(), target);
    }
  }

  // double unit_price = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_unit_price()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          4, this_._internal_unit_price(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:myapp.Order.Item)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Order_Item::ByteSizeLong(const MessageLite& base) {
  const Order_Item& this_ = static_cast<const Order_Item&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Order_Item::ByteSizeLong() const {
  const Order_Item& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:myapp.Order.Item)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // string sku = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_sku().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_sku());
      }
    }
    // string title = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_title().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_title());
      }
    }
    // double unit_price = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_unit_price()) != 0) {
        total_size += 9;
      }
    }
    // int32 quantity = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_quantity() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_quantity());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Order_Item::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<Order_Item*>(&to_msg);
  auto& from = static_cast<const Order_Item&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:myapp.Order.Item)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_sku().empty()) {
        _this->_internal_set_sku(from._internal_sku());
      } else {
        if (_this->_impl_.sku_.IsDefault()) {
          _this->_internal_set_sku("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_title().empty()) {
        _this->_internal_set_title(from._internal_title());
      } else {
        if (_this->_impl_.title_.IsDefault()) {
          _this->_internal_set_title("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_unit_price()) != 0) {
        _this->_impl_.unit_price_ = from._impl_.unit_price_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_quantity() != 0) {
        _this->_impl_.quantity_ = from._impl_.quantity_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Order_Item::CopyFrom(const Order_Item& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:myapp.Order.Item)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Order_Item::InternalSwap(Order_Item* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sku_, &other->_impl_.sku_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.title_, &other->_impl_.title_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Order_Item, _impl_.quantity_)
      + sizeof(Order_Item::_impl_.quantity_)
      - PROTOBUF_FIELD_OFFSET(Order_Item, _impl_.unit_price_)>(
          reinterpret_cast<char*>(&_impl_.unit_price_),
          reinterpret_cast<char*>(&other->_impl_.unit_price_));
}

::google::protobuf::Metadata Order_Item::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
Order_MetadataEntry_DoNotUse::Order_MetadataEntry_DoNotUse() : SuperType(Order_MetadataEntry_DoNotUse_get_class_data()) {}
Order_MetadataEntry_DoNotUse::Order_MetadataEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : SuperType(arena, Order_MetadataEntry_DoNotUse_get_class_data()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
Order_MetadataEntry_DoNotUse::Order_MetadataEntry_DoNotUse() : SuperType() {}
Order_MetadataEntry_DoNotUse::Order_MetadataEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Order_MetadataEntry_DoNotUse_class_data_ =
        Order_MetadataEntry_DoNotUse::InternalGenerateClassData_(Order_MetadataEntry_DoNotUse_globals_._default);

// including ~ all the vtables and everything they use become part
// of the same ~ SCC.
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Order_MetadataEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Order_MetadataEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Order_MetadataEntry_DoNotUse_class_data_.tc_table);
  return Order_MetadataEntry_DoNotUse_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Order_MetadataEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Order_MetadataEntry_DoNotUse_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&Order_MetadataEntry_DoNotUse_globals_));
  return Order_MetadataEntry_DoNotUse_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const Order_MetadataEntry_DoNotUse::ParseTableT_
    Order_MetadataEntry_DoNotUse::_table_ =
        Order_MetadataEntry_DoNotUse::InternalGenerateParseTable_(Order_MetadataEntry_DoNotUse_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
// ===================================================================

void Order::clear_buyer() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.buyer_ != nullptr) _impl_.buyer_->Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
void Order::clear_shipping_address() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.shipping_address_ != nullptr) _impl_.shipping_address_->Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
Order::Order(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Order_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:myapp.Order)
}
PROTOBUF_NDEBUG_INLINE Order::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::myapp::Order& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        item_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::myapp::Order,
              PROTOBUF_FIELD_OFFSET(::myapp::Order, _impl_.item_)>()
          , from.item_
        }
        ,
        tracking_number_(arena, from.tracking_number_),
        metadata_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::myapp::Order,
              PROTOBUF_FIELD_OFFSET(::myapp::Order, _impl_.metadata_)>()
          , from.metadata_
        }
     {}

Order::Order(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Order& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Order_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Order* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.buyer_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.buyer_)
                : nullptr;
  _impl_.shipping_address_ = (CheckHasBit(cached_has_bits, 0x00000008U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.shipping_address_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, order_id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, order_id_),
           offsetof(Impl_, status_) -
               offsetof(Impl_, order_id_) +
               sizeof(Impl_::status_));

  // @@protoc_insertion_point(copy_constructor:myapp.Order)
}
PROTOBUF_NDEBUG_INLINE Order::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        item_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::myapp::Order,
            PROTOBUF_FIELD_OFFSET(::myapp::Order, _impl_.item_)>()
         }
        ,
        tracking_number_(arena),
        metadata_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::myapp::Order,
            PROTOBUF_FIELD_OFFSET(::myapp::Order, _impl_.metadata_)>()
         }
     {}

inline void Order::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, buyer_),
           0,
           offsetof(Impl_, status_) -
               offsetof(Impl_, buyer_) +
               sizeof(Impl_::status_));
}
Order::~Order() {
  // @@protoc_insertion_point(destructor:myapp.Order)
  SharedDtor(*this);
}
inline void Order::SharedDtor(MessageLite& self) {
  Order& this_ = static_cast<Order&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.tracking_number_.Destroy();
  delete this_._impl_.buyer_;
  delete this_._impl_.shipping_address_;
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Order_class_data_ =
        Order::InternalGenerateClassData_(Order_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Order::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Order_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Order_class_data_.tc_table);
  return Order_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Order::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Order_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&Order_globals_));
  return Order_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const Order::ParseTableT_
    Order::_table_ =
        Order::InternalGenerateParseTable_(Order_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void Order::Clear() {
// @@protoc_insertion_point(message_clear_start:myapp.Order)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.item_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.tracking_number_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.buyer_ != nullptr);
      _impl_.buyer_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(_impl_.shipping_address_ != nullptr);
      _impl_.shipping_address_->Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000f0U)) {
    ::memset(&_impl_.order_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.status_) -
        reinterpret_cast<char*>(&_impl_.order_id_)) + sizeof(_impl_.status_));
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      _impl_.metadata_.Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Order::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Order& this_ = static_cast<const Order&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Order::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Order& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:myapp.Order)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int64 order_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_order_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
              stream, this_._internal_order_id(), target);
    }
  }

  // .myapp.User buyer = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.buyer_, this_._impl_.buyer_->GetCachedSize(), target,
        stream);
  }

  // .myapp.Address shipping_address = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.shipping_address_, this_._impl_.shipping_address_->GetCachedSize(), target,
        stream);
  }

  // repeated .myapp.Order.Item item = 4;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_item_size());
         i < n; i++) {
      const auto& repfield = this_._internal_item().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              4, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // .myapp.Order.OrderStatus status = 5;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_status() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          5, this_._internal_status(), target);
    }
  }

  // double total_amount = 6;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_total_amount()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          6, this_._internal_total_amount(), target);
    }
  }

  // map<string, string> metadata = 7;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (!this_._internal_metadata().empty()) {
      using MapType = ::google::protobuf::Map<::std::string, ::std::string>;
      using WireHelper = _pbi::MapEntryFuncs<::std::string, ::std::string,
                                     _pbi::WireFormatLite::TYPE_STRING,
                                     _pbi::WireFormatLite::TYPE_STRING>;
      const auto& field = this_._internal_metadata();

      if (stream->IsSerializationDeterministic() && field.size() > 1) {
        for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
          target = WireHelper::InternalSerialize(
              7, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "myapp.Order.metadata");
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "myapp.Order.metadata");
        }
      } else {
        for (const auto& entry : field) {
          target = WireHelper::InternalSerialize(
              7, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "myapp.Order.metadata");
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "myapp.Order.metadata");
        }
      }
    }
  }

  // optional string tracking_number = 8;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::std::string& _s = this_._internal_tracking_number();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "myapp.Order.tracking_number");
    target = stream->WriteStringMaybeAliased(8, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:myapp.Order)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Order::ByteSizeLong(const MessageLite& base) {
  const Order& this_ = static_cast<const Order&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Order::ByteSizeLong() const {
  const Order& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:myapp.Order)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // repeated .myapp.Order.Item item = 4;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_item_size();
      for (const auto& msg : this_._internal_item()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // optional string tracking_number = 8;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_tracking_number());
    }
    // .myapp.User buyer = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.buyer_);
    }
    // .myapp.Address shipping_address = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.shipping_address_);
    }
    // int64 order_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_order_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_order_id());
      }
    }
    // double total_amount = 6;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_total_amount()) != 0) {
        total_size += 9;
      }
    }
    // .myapp.Order.OrderStatus status = 5;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_status() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
      }
    }
    // map<string, string> metadata = 7;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_metadata_size());
      for (const auto& entry : this_._internal_metadata()) {
        total_size += _pbi::MapEntryFuncs<::std::string, ::std::string,
                                       _pbi::WireFormatLite::TYPE_STRING,
                                       _pbi::WireFormatLite::TYPE_STRING>::ByteSizeLong(entry.first, entry.second);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Order::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<Order*>(&to_msg);
  auto& from = static_cast<const Order&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:myapp.Order)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_item()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_item());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_tracking_number(from._internal_tracking_number());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.buyer_ != nullptr);
      if (_this->_impl_.buyer_ == nullptr) {
        _this->_impl_.buyer_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.buyer_);
      } else {
        _this->_impl_.buyer_->MergeFrom(*from._impl_.buyer_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(from._impl_.shipping_address_ != nullptr);
      if (_this->_impl_.shipping_address_ == nullptr) {
        _this->_impl_.shipping_address_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.shipping_address_);
      } else {
        _this->_impl_.shipping_address_->MergeFrom(*from._impl_.shipping_address_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_order_id() != 0) {
        _this->_impl_.order_id_ = from._impl_.order_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_total_amount()) != 0) {
        _this->_impl_.total_amount_ = from._impl_.total_amount_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_status() != 0) {
        _this->_impl_.status_ = from._impl_.status_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      _this->_impl_.metadata_.MergeFrom(from._impl_.metadata_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Order::CopyFrom(const Order& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:myapp.Order)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Order::InternalSwap(Order* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.item_.InternalSwap(&other->_impl_.item_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.tracking_number_, &other->_impl_.tracking_number_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Order, _impl_.status_)
      + sizeof(Order::_impl_.status_)
      - PROTOBUF_FIELD_OFFSET(Order, _impl_.buyer_)>(
          reinterpret_cast<char*>(&_impl_.buyer_),
          reinterpret_cast<char*>(&other->_impl_.buyer_));
  _impl_.metadata_.InternalSwap(&other->_impl_.metadata_);
}

::google::protobuf::Metadata Order::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace myapp
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_orders_2forder_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
