// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: orders/order.proto
// Protobuf C++ Version: 7.35.1

#ifndef orders_2forder_2eproto_2epb_2eh
#define orders_2forder_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7035001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_type_handler.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field.h"
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "users/user.pb.h"
#include "common/address.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_orders_2forder_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_orders_2forder_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_orders_2forder_2eproto;
}  // extern "C"
namespace myapp {
enum Order_OrderStatus : int;
extern const uint32_t Order_OrderStatus_internal_data_[];
class Order;
struct OrderGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern OrderGlobalsTypeInternal Order_globals_;
extern const ::google::protobuf::internal::ClassDataFull Order_class_data_;
#else
extern const OrderGlobalsTypeInternal Order_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class Order_Item;
struct Order_ItemGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern Order_ItemGlobalsTypeInternal Order_Item_globals_;
extern const ::google::protobuf::internal::ClassDataFull Order_Item_class_data_;
#else
extern const Order_ItemGlobalsTypeInternal Order_Item_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class Order_MetadataEntry_DoNotUse;
struct Order_MetadataEntry_DoNotUseGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern Order_MetadataEntry_DoNotUseGlobalsTypeInternal Order_MetadataEntry_DoNotUse_globals_;
extern const ::google::protobuf::internal::ClassDataFull Order_MetadataEntry_DoNotUse_class_data_;
#else
extern const Order_MetadataEntry_DoNotUseGlobalsTypeInternal Order_MetadataEntry_DoNotUse_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace myapp
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::myapp::Order_OrderStatus_internal_data_>
    internal::EnumTraitsImpl::value<::myapp::Order_OrderStatus>;
}  // namespace protobuf
}  // namespace google

namespace myapp {
enum Order_OrderStatus : int {
  Order_OrderStatus_ORDER_STATUS_UNKNOWN = 0,
  Order_OrderStatus_ORDER_STATUS_PENDING = 1,
  Order_OrderStatus_ORDER_STATUS_PAID = 2,
  Order_OrderStatus_ORDER_STATUS_SHIPPED = 3,
  Order_OrderStatus_ORDER_STATUS_CANCELLED = 4,
  Order_OrderStatus_Order_OrderStatus_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Order_OrderStatus_Order_OrderStatus_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Order_OrderStatus_internal_data_[];
inline constexpr Order_OrderStatus Order_OrderStatus_OrderStatus_MIN =
    static_cast<Order_OrderStatus>(0);
inline constexpr Order_OrderStatus Order_OrderStatus_OrderStatus_MAX =
    static_cast<Order_OrderStatus>(4);
[[nodiscard]] inline bool Order_OrderStatus_IsValid(int value) {
  return 0 <= value && value <= 4;
}
inline constexpr int Order_OrderStatus_OrderStatus_ARRAYSIZE = 4 + 1;
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
Order_OrderStatus_descriptor();
[[nodiscard]] inline auto ProtobufInternalGetEnumDescriptor(Order_OrderStatus) {
  return Order_OrderStatus_descriptor();
}
template <typename T>
[[nodiscard]] const ::std::string& Order_OrderStatus_Name(T value) {
  static_assert(::std::is_same<T, Order_OrderStatus>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to OrderStatus_Name().");
  return Order_OrderStatus_Name(static_cast<Order_OrderStatus>(value));
}
template <>
[[nodiscard]] inline const ::std::string& Order_OrderStatus_Name(Order_OrderStatus value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Order_OrderStatus_descriptor, 0, 4>(
      static_cast<int>(value));
}
[[nodiscard]] inline bool Order_OrderStatus_Parse(
    ::absl::string_view name, Order_OrderStatus* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Order_OrderStatus>(Order_OrderStatus_descriptor(), name,
                                           value);
}
using ::google::protobuf::internal::generated_enum::AbslParseFlag;
using ::google::protobuf::internal::generated_enum::AbslUnparseFlag;

// ===================================================================


// -------------------------------------------------------------------

class PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED Order_MetadataEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::std::string, ::std::string,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<::std::string, ::std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  Order_MetadataEntry_DoNotUse();
  template <typename = void>
  explicit constexpr Order_MetadataEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);
  explicit Order_MetadataEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_message_globals() {
    return &Order_MetadataEntry_DoNotUse_globals_;
  }


  static constexpr auto InternalGenerateClassData_(
      const ::google::protobuf::MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_orders_2forder_2eproto;
  friend ::google::protobuf::internal::PrivateAccess;
  friend Order_MetadataEntry_DoNotUseGlobalsTypeInternal;

  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<1, 2,
                          0, 42,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED Order_Item final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:myapp.Order.Item) */ {
 public:
  inline Order_Item() : Order_Item(nullptr) {}
  ~Order_Item() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Order_Item* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Order_Item));
  }
#endif

  template <typename = void>
  explicit constexpr Order_Item(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline Order_Item(const Order_Item& from) : Order_Item(nullptr, from) {}
  inline Order_Item(Order_Item&& from) noexcept : Order_Item(nullptr, ::std::move(from)) {}
  inline Order_Item& operator=(const Order_Item& from) {
    CopyFrom(from);
    return *this;
  }
  inline Order_Item& operator=(Order_Item&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const Order_Item& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<Order_Item>(&Order_Item_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Order_Item& a, Order_Item& b) { a.Swap(&b); }
  inline void Swap(Order_Item* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Order_Item* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] Order_Item* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Order_Item>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Order_Item& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Order_Item& from) { Order_Item::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Order_Item* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "myapp.Order.Item"; }

  explicit Order_Item(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Order_Item(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Order_Item& from);
  Order_Item(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Order_Item&& from) noexcept
      : Order_Item(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSkuFieldNumber = 1,
    kTitleFieldNumber = 2,
    kUnitPriceFieldNumber = 4,
    kQuantityFieldNumber = 3,
  };
  // string sku = 1;
  void clear_sku() ;
  [[nodiscard]] const ::std::string& sku() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_sku(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_sku();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_sku();
  void set_allocated_sku(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_sku() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_sku(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_sku();

  public:
  // string title = 2;
  void clear_title() ;
  [[nodiscard]] const ::std::string& title() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_title(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_title();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_title();
  void set_allocated_title(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_title() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_title(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_title();

  public:
  // double unit_price = 4;
  void clear_unit_price() ;
  [[nodiscard]] double unit_price() const;
  void set_unit_price(double value);

  private:
  double _internal_unit_price() const;
  void _internal_set_unit_price(double value);

  public:
  // int32 quantity = 3;
  void clear_quantity() ;
  [[nodiscard]] ::int32_t quantity() const;
  void set_quantity(::int32_t value);

  private:
  ::int32_t _internal_quantity() const;
  void _internal_set_quantity(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:myapp.Order.Item)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<2, 4,
                          0, 33,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Order_Item& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr sku_;
    ::google::protobuf::internal::ArenaStringPtr title_;
    double unit_price_;
    ::int32_t quantity_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_orders_2forder_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED Order final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:myapp.Order) */ {
 public:
  inline Order() : Order(nullptr) {}
  ~Order() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Order* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Order));
  }
#endif

  template <typename = void>
  explicit constexpr Order(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline Order(const Order& from) : Order(nullptr, from) {}
  inline Order(Order&& from) noexcept : Order(nullptr, ::std::move(from)) {}
  inline Order& operator=(const Order& from) {
    CopyFrom(from);
    return *this;
  }
  inline Order& operator=(Order&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const Order& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<Order>(&Order_globals_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Order& a, Order& b) { a.Swap(&b); }
  inline void Swap(Order* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Order* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] Order* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Order>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Order& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Order& from) { Order::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Order* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "myapp.Order"; }

  explicit Order(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Order(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Order& from);
  Order(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Order&& from) noexcept
      : Order(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Item = Order_Item;
  using OrderStatus = Order_OrderStatus;
  static constexpr OrderStatus ORDER_STATUS_UNKNOWN = Order_OrderStatus_ORDER_STATUS_UNKNOWN;
  static constexpr OrderStatus ORDER_STATUS_PENDING = Order_OrderStatus_ORDER_STATUS_PENDING;
  static constexpr OrderStatus ORDER_STATUS_PAID = Order_OrderStatus_ORDER_STATUS_PAID;
  static constexpr OrderStatus ORDER_STATUS_SHIPPED = Order_OrderStatus_ORDER_STATUS_SHIPPED;
  static constexpr OrderStatus ORDER_STATUS_CANCELLED = Order_OrderStatus_ORDER_STATUS_CANCELLED;
  [[nodiscard]] static inline bool OrderStatus_IsValid(int value) {
    return Order_OrderStatus_IsValid(value);
  }
  static constexpr OrderStatus OrderStatus_MIN = Order_OrderStatus_OrderStatus_MIN;
  static constexpr OrderStatus OrderStatus_MAX = Order_OrderStatus_OrderStatus_MAX;
  static constexpr int OrderStatus_ARRAYSIZE = Order_OrderStatus_OrderStatus_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL OrderStatus_descriptor() {
    return Order_OrderStatus_descriptor();
  }
  template <typename T>
  [[nodiscard]] static inline const ::std::string& OrderStatus_Name(T value) {
    return Order_OrderStatus_Name(value);
  }
  [[nodiscard]] static inline bool OrderStatus_Parse(
      ::absl::string_view name, OrderStatus* PROTOBUF_NONNULL value) {
    return Order_OrderStatus_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kItemFieldNumber = 4,
    kTrackingNumberFieldNumber = 8,
    kBuyerFieldNumber = 2,
    kShippingAddressFieldNumber = 3,
    kOrderIdFieldNumber = 1,
    kTotalAmountFieldNumber = 6,
    kStatusFieldNumber = 5,
    kMetadataFieldNumber = 7,
  };
  // repeated .myapp.Order.Item item = 4;
  [[nodiscard]] int item_size()
      const;
  private:
  int _internal_item_size() const;

  public:
  void clear_item() ;
  [[nodiscard]] const ::myapp::Order_Item& item(int index) const;
  [[nodiscard]] ::myapp::Order_Item* PROTOBUF_NONNULL mutable_item(int index);
  ::myapp::Order_Item* PROTOBUF_NONNULL add_item();
  [[nodiscard]] const ::google::protobuf::RepeatedPtrField<::myapp::Order_Item>&
  item() const;
  [[nodiscard]] ::google::protobuf::RepeatedPtrField<::myapp::Order_Item>* PROTOBUF_NONNULL
  mutable_item();

  private:
  const ::google::protobuf::RepeatedPtrField<::myapp::Order_Item>& _internal_item() const;
  ::google::protobuf::RepeatedPtrField<::myapp::Order_Item>* PROTOBUF_NONNULL _internal_mutable_item();

  public:
  // optional string tracking_number = 8;
  [[nodiscard]] bool has_tracking_number()
      const;
  void clear_tracking_number() ;
  [[nodiscard]] const ::std::string& tracking_number() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_tracking_number(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_tracking_number();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_tracking_number();
  void set_allocated_tracking_number(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_tracking_number() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_tracking_number(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_tracking_number();

  public:
  // .myapp.User buyer = 2;
  [[nodiscard]] bool has_buyer()
      const;
  void clear_buyer() ;
  [[nodiscard]] const ::myapp::User& buyer() const;
  [[nodiscard]] ::myapp::User* PROTOBUF_NULLABLE release_buyer();
  ::myapp::User* PROTOBUF_NONNULL mutable_buyer();
  void set_allocated_buyer(::myapp::User* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_buyer(::myapp::User* PROTOBUF_NULLABLE value);
  ::myapp::User* PROTOBUF_NULLABLE unsafe_arena_release_buyer();

  private:
  const ::myapp::User& _internal_buyer() const;
  ::myapp::User* PROTOBUF_NONNULL _internal_mutable_buyer();

  public:
  // .myapp.Address shipping_address = 3;
  [[nodiscard]] bool has_shipping_address()
      const;
  void clear_shipping_address() ;
  [[nodiscard]] const ::myapp::Address& shipping_address() const;
  [[nodiscard]] ::myapp::Address* PROTOBUF_NULLABLE release_shipping_address();
  ::myapp::Address* PROTOBUF_NONNULL mutable_shipping_address();
  void set_allocated_shipping_address(::myapp::Address* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_shipping_address(::myapp::Address* PROTOBUF_NULLABLE value);
  ::myapp::Address* PROTOBUF_NULLABLE unsafe_arena_release_shipping_address();

  private:
  const ::myapp::Address& _internal_shipping_address() const;
  ::myapp::Address* PROTOBUF_NONNULL _internal_mutable_shipping_address();

  public:
  // int64 order_id = 1;
  void clear_order_id() ;
  [[nodiscard]] ::int64_t order_id() const;
  void set_order_id(::int64_t value);

  private:
  ::int64_t _internal_order_id() const;
  void _internal_set_order_id(::int64_t value);

  public:
  // double total_amount = 6;
  void clear_total_amount() ;
  [[nodiscard]] double total_amount() const;
  void set_total_amount(double value);

  private:
  double _internal_total_amount() const;
  void _internal_set_total_amount(double value);

  public:
  // .myapp.Order.OrderStatus status = 5;
  void clear_status() ;
  [[nodiscard]] ::myapp::Order_OrderStatus status() const;
  void set_status(::myapp::Order_OrderStatus value);

  private:
  ::myapp::Order_OrderStatus _internal_status() const;
  void _internal_set_status(::myapp::Order_OrderStatus value);

  public:
  // map<string, string> metadata = 7;
  [[nodiscard]] int metadata_size()
      const;
  private:
  int _internal_metadata_size() const;

  public:
  void clear_metadata() ;
  [[nodiscard]] const ::google::protobuf::Map<::std::string, ::std::string>& metadata() const;
  [[nodiscard]] ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL mutable_metadata();

  private:
  const ::google::protobuf::Map<::std::string, ::std::string>& _internal_metadata() const;
  ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL _internal_mutable_metadata();

  public:
  // @@protoc_insertion_point(class_scope:myapp.Order)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<3, 8,
                          4, 51,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Order& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::myapp::Order_Item > item_;
    ::google::protobuf::internal::ArenaStringPtr tracking_number_;
    ::myapp::User* PROTOBUF_NULLABLE buyer_;
    ::myapp::Address* PROTOBUF_NULLABLE shipping_address_;
    ::int64_t order_id_;
    double total_amount_;
    int status_;
    ::google::protobuf::internal::MapField<Order_MetadataEntry_DoNotUse, ::std::string, ::std::string> metadata_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_orders_2forder_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Order_Item

// string sku = 1;
inline void Order_Item::clear_sku() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sku_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& Order_Item::sku() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:myapp.Order.Item.sku)
  return _internal_sku();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Order_Item::set_sku(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.sku_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:myapp.Order.Item.sku)
}
inline ::std::string* PROTOBUF_NONNULL Order_Item::mutable_sku()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_sku();
  // @@protoc_insertion_point(field_mutable:myapp.Order.Item.sku)
  return _s;
}
inline const ::std::string& Order_Item::_internal_sku() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sku_.Get();
}
inline void Order_Item::_internal_set_sku(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sku_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Order_Item::_internal_mutable_sku() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.sku_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Order_Item::release_sku() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:myapp.Order.Item.sku)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.sku_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.sku_.Set("", GetArena());
  }
  return released;
}
inline void Order_Item::set_allocated_sku(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.sku_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.sku_.IsDefault()) {
    _impl_.sku_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:myapp.Order.Item.sku)
}

// string title = 2;
inline void Order_Item::clear_title() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.title_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::std::string& Order_Item::title() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:myapp.Order.Item.title)
  return _internal_title();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Order_Item::set_title(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.title_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:myapp.Order.Item.title)
}
inline ::std::string* PROTOBUF_NONNULL Order_Item::mutable_title()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_title();
  // @@protoc_insertion_point(field_mutable:myapp.Order.Item.title)
  return _s;
}
inline const ::std::string& Order_Item::_internal_title() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.title_.Get();
}
inline void Order_Item::_internal_set_title(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.title_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Order_Item::_internal_mutable_title() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.title_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Order_Item::release_title() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:myapp.Order.Item.title)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.title_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.title_.Set("", GetArena());
  }
  return released;
}
inline void Order_Item::set_allocated_title(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.title_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.title_.IsDefault()) {
    _impl_.title_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:myapp.Order.Item.title)
}

// int32 quantity = 3;
inline void Order_Item::clear_quantity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.quantity_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline ::int32_t Order_Item::quantity() const {
  // @@protoc_insertion_point(field_get:myapp.Order.Item.quantity)
  return _internal_quantity();
}
inline void Order_Item::set_quantity(::int32_t value) {
  _internal_set_quantity(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:myapp.Order.Item.quantity)
}
inline ::int32_t Order_Item::_internal_quantity() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.quantity_;
}
inline void Order_Item::_internal_set_quantity(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.quantity_ = value;
}

// double unit_price = 4;
inline void Order_Item::clear_unit_price() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.unit_price_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline double Order_Item::unit_price() const {
  // @@protoc_insertion_point(field_get:myapp.Order.Item.unit_price)
  return _internal_unit_price();
}
inline void Order_Item::set_unit_price(double value) {
  _internal_set_unit_price(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:myapp.Order.Item.unit_price)
}
inline double Order_Item::_internal_unit_price() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.unit_price_;
}
inline void Order_Item::_internal_set_unit_price(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.unit_price_ = value;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Order

// int64 order_id = 1;
inline void Order::clear_order_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.order_id_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
}
inline ::int64_t Order::order_id() const {
  // @@protoc_insertion_point(field_get:myapp.Order.order_id)
  return _internal_order_id();
}
inline void Order::set_order_id(::int64_t value) {
  _internal_set_order_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:myapp.Order.order_id)
}
inline ::int64_t Order::_internal_order_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.order_id_;
}
inline void Order::_internal_set_order_id(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.order_id_ = value;
}

// .myapp.User buyer = 2;
inline bool Order::has_buyer() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  PROTOBUF_ASSUME(!value || _impl_.buyer_ != nullptr);
  return value;
}
inline const ::myapp::User& Order::_internal_buyer() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::myapp::User* p = _impl_.buyer_;
  return p != nullptr ? *p : *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<::myapp::User>(&::myapp::User_globals_);
}
inline const ::myapp::User& Order::buyer() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:myapp.Order.buyer)
  return _internal_buyer();
}
inline void Order::unsafe_arena_set_allocated_buyer(
    ::myapp::User* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.buyer_);
  }
  _impl_.buyer_ = reinterpret_cast<::myapp::User*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:myapp.Order.buyer)
}
inline ::myapp::User* PROTOBUF_NULLABLE Order::release_buyer() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::myapp::User* released = _impl_.buyer_;
  _impl_.buyer_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::myapp::User* PROTOBUF_NULLABLE Order::unsafe_arena_release_buyer() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:myapp.Order.buyer)

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::myapp::User* temp = _impl_.buyer_;
  _impl_.buyer_ = nullptr;
  return temp;
}
inline ::myapp::User* PROTOBUF_NONNULL Order::_internal_mutable_buyer() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.buyer_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::myapp::User>(GetArena());
    _impl_.buyer_ = reinterpret_cast<::myapp::User*>(p);
  }
  return _impl_.buyer_;
}
inline ::myapp::User* PROTOBUF_NONNULL Order::mutable_buyer()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::myapp::User* _msg = _internal_mutable_buyer();
  // @@protoc_insertion_point(field_mutable:myapp.Order.buyer)
  return _msg;
}
inline void Order::set_allocated_buyer(::myapp::User* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.buyer_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }

  _impl_.buyer_ = reinterpret_cast<::myapp::User*>(value);
  // @@protoc_insertion_point(field_set_allocated:myapp.Order.buyer)
}

// .myapp.Address shipping_address = 3;
inline bool Order::has_shipping_address() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  PROTOBUF_ASSUME(!value || _impl_.shipping_address_ != nullptr);
  return value;
}
inline const ::myapp::Address& Order::_internal_shipping_address() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::myapp::Address* p = _impl_.shipping_address_;
  return p != nullptr ? *p : *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<::myapp::Address>(&::myapp::Address_globals_);
}
inline const ::myapp::Address& Order::shipping_address() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:myapp.Order.shipping_address)
  return _internal_shipping_address();
}
inline void Order::unsafe_arena_set_allocated_shipping_address(
    ::myapp::Address* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.shipping_address_);
  }
  _impl_.shipping_address_ = reinterpret_cast<::myapp::Address*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:myapp.Order.shipping_address)
}
inline ::myapp::Address* PROTOBUF_NULLABLE Order::release_shipping_address() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::myapp::Address* released = _impl_.shipping_address_;
  _impl_.shipping_address_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::myapp::Address* PROTOBUF_NULLABLE Order::unsafe_arena_release_shipping_address() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:myapp.Order.shipping_address)

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::myapp::Address* temp = _impl_.shipping_address_;
  _impl_.shipping_address_ = nullptr;
  return temp;
}
inline ::myapp::Address* PROTOBUF_NONNULL Order::_internal_mutable_shipping_address() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.shipping_address_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::myapp::Address>(GetArena());
    _impl_.shipping_address_ = reinterpret_cast<::myapp::Address*>(p);
  }
  return _impl_.shipping_address_;
}
inline ::myapp::Address* PROTOBUF_NONNULL Order::mutable_shipping_address()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::myapp::Address* _msg = _internal_mutable_shipping_address();
  // @@protoc_insertion_point(field_mutable:myapp.Order.shipping_address)
  return _msg;
}
inline void Order::set_allocated_shipping_address(::myapp::Address* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.shipping_address_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }

  _impl_.shipping_address_ = reinterpret_cast<::myapp::Address*>(value);
  // @@protoc_insertion_point(field_set_allocated:myapp.Order.shipping_address)
}

// repeated .myapp.Order.Item item = 4;
inline int Order::_internal_item_size() const {
  return _internal_item().size();
}
inline int Order::item_size() const {
  return _internal_item_size();
}
inline void Order::clear_item() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.item_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::myapp::Order_Item& Order::item(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:myapp.Order.item)
  return _internal_item().Get(index);
}
inline ::myapp::Order_Item* PROTOBUF_NONNULL Order::mutable_item(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:myapp.Order.item)
  return _internal_mutable_item()->Mutable(index);
}
inline ::myapp::Order_Item* PROTOBUF_NONNULL Order::add_item()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::myapp::Order_Item* _add =
      _internal_mutable_item()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:myapp.Order.item)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::myapp::Order_Item>& Order::item() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:myapp.Order.item)
  return _internal_item();
}
inline ::google::protobuf::RepeatedPtrField<::myapp::Order_Item>* PROTOBUF_NONNULL
Order::mutable_item() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:myapp.Order.item)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_item();
}
inline const ::google::protobuf::RepeatedPtrField<::myapp::Order_Item>&
Order::_internal_item() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.item_;
}
inline ::google::protobuf::RepeatedPtrField<::myapp::Order_Item>* PROTOBUF_NONNULL
Order::_internal_mutable_item() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.item_;
}

// .myapp.Order.OrderStatus status = 5;
inline void Order::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
}
inline ::myapp::Order_OrderStatus Order::status() const {
  // @@protoc_insertion_point(field_get:myapp.Order.status)
  return _internal_status();
}
inline void Order::set_status(::myapp::Order_OrderStatus value) {
  _internal_set_status(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:myapp.Order.status)
}
inline ::myapp::Order_OrderStatus Order::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::myapp::Order_OrderStatus>(_impl_.status_);
}
inline void Order::_internal_set_status(::myapp::Order_OrderStatus value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// double total_amount = 6;
inline void Order::clear_total_amount() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_amount_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
}
inline double Order::total_amount() const {
  // @@protoc_insertion_point(field_get:myapp.Order.total_amount)
  return _internal_total_amount();
}
inline void Order::set_total_amount(double value) {
  _internal_set_total_amount(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:myapp.Order.total_amount)
}
inline double Order::_internal_total_amount() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.total_amount_;
}
inline void Order::_internal_set_total_amount(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_amount_ = value;
}

// map<string, string> metadata = 7;
inline int Order::_internal_metadata_size() const {
  return _internal_metadata().size();
}
inline int Order::metadata_size() const {
  return _internal_metadata_size();
}
inline void Order::clear_metadata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.metadata_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000080U);
}
inline const ::google::protobuf::Map<::std::string, ::std::string>& Order::_internal_metadata() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.metadata_.GetMap();
}
inline const ::google::protobuf::Map<::std::string, ::std::string>& Order::metadata() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:myapp.Order.metadata)
  return _internal_metadata();
}
inline ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL Order::_internal_mutable_metadata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.metadata_.MutableMap();
}
inline ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL Order::mutable_metadata()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_mutable_map:myapp.Order.metadata)
  return _internal_mutable_metadata();
}

// optional string tracking_number = 8;
inline bool Order::has_tracking_number() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void Order::clear_tracking_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tracking_number_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::std::string& Order::tracking_number() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:myapp.Order.tracking_number)
  return _internal_tracking_number();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Order::set_tracking_number(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.tracking_number_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:myapp.Order.tracking_number)
}
inline ::std::string* PROTOBUF_NONNULL Order::mutable_tracking_number()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_tracking_number();
  // @@protoc_insertion_point(field_mutable:myapp.Order.tracking_number)
  return _s;
}
inline const ::std::string& Order::_internal_tracking_number() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tracking_number_.Get();
}
inline void Order::_internal_set_tracking_number(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tracking_number_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Order::_internal_mutable_tracking_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.tracking_number_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Order::release_tracking_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:myapp.Order.tracking_number)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.tracking_number_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.tracking_number_.Set("", GetArena());
  }
  return released;
}
inline void Order::set_allocated_tracking_number(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.tracking_number_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.tracking_number_.IsDefault()) {
    _impl_.tracking_number_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:myapp.Order.tracking_number)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace myapp


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::myapp::Order_OrderStatus> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::myapp::Order_OrderStatus>() {
  return ::myapp::Order_OrderStatus_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // orders_2forder_2eproto_2epb_2eh
