#include <iostream>

#include "two_sum.h"
#include "best_time_buy_sell.h"
#include "max_subarray.h"
#include "merge_intervals.h"
#include "product_except_self.h"
#include "len_of_longest_substring.h"
#include "group_anagram.h"
#include "valid_parentheses.h"
#include "container_most_water.h"
#include "three_sum.h"
#include "reverse_linked_list.h"
#include "detect_cycle_in_ll.h"
#include "merge_two_sorted_lists.h"
#include "remove_nth_node_from_end.h"
#include "lru_cache.h"
#include "max_depth_binary_tree.h"
#include "validate_bst.h"
#include "binary_tree_level_order_traversal.h"
#include "lowest_common_ancestor.h"
#include "ser_des_binary_tree.h"
#include "number_of_islands.h"
#include "clone_graph.h"
#include "topological_sort.h"
#include "word_ladder.h"
#include "climbing_stairs.h"
#include "coin_change.h"
#include "longest_common_subsequence.h"
#include "longest_increasing_subsequence.h"
#include "edit_distance.h"
#include "house_robber.h"
#include "word_break.h"
#include "knapsack01.h"
#include "min_stack.h"

int main(int argc, char *argv[]) {
    // two_sum::demo();
    // best_time_buy_sell::demo();
    // max_subarray::demo();
    // merge_intervals::demo();
    // product_except_self::demo();
    // len_of_longest_substring::demo();
    // group_anagram::demo();
    // valid_parentheses::demo();
    // container_most_water::demo();
    // three_sum::demo();
    // reverse_linked_list::demo();
    // detect_cycle_in_ll::demo();
    // merge_two_sorted_lists::demo();
    // remove_nth_node_from_end::demo();
    // lru_cache::demo();
    // max_depth_binary_tree::demo();
    // validate_bst::demo();
    // binary_tree_level_order_traversal::demo();
    // lowest_common_ancestor::demo();
    // ser_des_binary_tree::demo();
    // number_of_islands::demo();
    // clone_graph::demo();
    // topological_sort::demo();
    // word_ladder::demo();
    // climbing_stairs::demo();
    // coin_change::demo();
    // longest_common_subsequence::demo();
    // longest_increasing_subsequence::demo();
    // edit_distance::demo();
    // house_robber::demo();
    // word_break::demo();
    // knapsack01::demo();
    min_stack::demo();
}
