// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: users/user.proto
// Protobuf C++ Version: 7.35.1

#ifndef users_2fuser_2eproto_2epb_2eh
#define users_2fuser_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7035001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_type_handler.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field.h"
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "common/address.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_users_2fuser_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_users_2fuser_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_users_2fuser_2eproto;
}  // extern "C"
namespace myapp {
enum User_Status : int;
extern const uint32_t User_Status_internal_data_[];
class User;
struct UserGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern UserGlobalsTypeInternal User_globals_;
extern const ::google::protobuf::internal::ClassDataFull User_class_data_;
#else
extern const UserGlobalsTypeInternal User_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class User_PreferencesEntry_DoNotUse;
struct User_PreferencesEntry_DoNotUseGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern User_PreferencesEntry_DoNotUseGlobalsTypeInternal User_PreferencesEntry_DoNotUse_globals_;
extern const ::google::protobuf::internal::ClassDataFull User_PreferencesEntry_DoNotUse_class_data_;
#else
extern const User_PreferencesEntry_DoNotUseGlobalsTypeInternal User_PreferencesEntry_DoNotUse_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace myapp
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::myapp::User_Status_internal_data_>
    internal::EnumTraitsImpl::value<::myapp::User_Status>;
}  // namespace protobuf
}  // namespace google

namespace myapp {
enum User_Status : int {
  User_Status_STATUS_UNKNOWN = 0,
  User_Status_STATUS_ACTIVE = 1,
  User_Status_STATUS_SUSPEND = 2,
  User_Status_STATUS_DELETED = 3,
  User_Status_User_Status_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  User_Status_User_Status_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t User_Status_internal_data_[];
inline constexpr User_Status User_Status_Status_MIN =
    static_cast<User_Status>(0);
inline constexpr User_Status User_Status_Status_MAX =
    static_cast<User_Status>(3);
[[nodiscard]] inline bool User_Status_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int User_Status_Status_ARRAYSIZE = 3 + 1;
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
User_Status_descriptor();
[[nodiscard]] inline auto ProtobufInternalGetEnumDescriptor(User_Status) {
  return User_Status_descriptor();
}
template <typename T>
[[nodiscard]] const ::std::string& User_Status_Name(T value) {
  static_assert(::std::is_same<T, User_Status>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Status_Name().");
  return User_Status_Name(static_cast<User_Status>(value));
}
template <>
[[nodiscard]] inline const ::std::string& User_Status_Name(User_Status value) {
  return ::google::protobuf::internal::NameOfDenseEnum<User_Status_descriptor, 0, 3>(
      static_cast<int>(value));
}
[[nodiscard]] inline bool User_Status_Parse(
    ::absl::string_view name, User_Status* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<User_Status>(User_Status_descriptor(), name,
                                           value);
}
using ::google::protobuf::internal::generated_enum::AbslParseFlag;
using ::google::protobuf::internal::generated_enum::AbslUnparseFlag;

// ===================================================================


// -------------------------------------------------------------------

class PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED User_PreferencesEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::std::string, ::std::string,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<::std::string, ::std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  User_PreferencesEntry_DoNotUse();
  template <typename = void>
  explicit constexpr User_PreferencesEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);
  explicit User_PreferencesEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_message_globals() {
    return &User_PreferencesEntry_DoNotUse_globals_;
  }


  static constexpr auto InternalGenerateClassData_(
      const ::google::protobuf::MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_users_2fuser_2eproto;
  friend ::google::protobuf::internal::PrivateAccess;
  friend User_PreferencesEntry_DoNotUseGlobalsTypeInternal;

  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<1, 2,
                          0, 44,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED User final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:myapp.User) */ {
 public:
  inline User() : User(nullptr) {}
  ~User() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(User* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(User));
  }
#endif

  template <typename = void>
  explicit constexpr User(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline User(const User& from) : User(nullptr, from) {}
  inline User(User&& from) noexcept : User(nullptr, ::std::move(from)) {}
  inline User& operator=(const User& from) {
    CopyFrom(from);
    return *this;
  }
  inline User& operator=(User&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const User& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<User>(&User_globals_);
  }
  enum ContactMethodCase {
    kPhone = 10,
    kTelegramHandle = 11,
    CONTACT_METHOD_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(User& a, User& b) { a.Swap(&b); }
  inline void Swap(User* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(User* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] User* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<User>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const User& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const User& from) { User::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(User* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "myapp.User"; }

  explicit User(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  User(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const User& from);
  User(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, User&& from) noexcept
      : User(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Status = User_Status;
  static constexpr Status STATUS_UNKNOWN = User_Status_STATUS_UNKNOWN;
  static constexpr Status STATUS_ACTIVE = User_Status_STATUS_ACTIVE;
  static constexpr Status STATUS_SUSPEND = User_Status_STATUS_SUSPEND;
  static constexpr Status STATUS_DELETED = User_Status_STATUS_DELETED;
  [[nodiscard]] static inline bool Status_IsValid(int value) {
    return User_Status_IsValid(value);
  }
  static constexpr Status Status_MIN = User_Status_Status_MIN;
  static constexpr Status Status_MAX = User_Status_Status_MAX;
  static constexpr int Status_ARRAYSIZE = User_Status_Status_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Status_descriptor() {
    return User_Status_descriptor();
  }
  template <typename T>
  [[nodiscard]] static inline const ::std::string& Status_Name(T value) {
    return User_Status_Name(value);
  }
  [[nodiscard]] static inline bool Status_Parse(
      ::absl::string_view name, Status* PROTOBUF_NONNULL value) {
    return User_Status_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kAddressesFieldNumber = 8,
    kNameFieldNumber = 2,
    kEmailFieldNumber = 3,
    kAvatarFieldNumber = 6,
    kIdFieldNumber = 1,
    kIsVerifiedFieldNumber = 4,
    kBalanceFieldNumber = 5,
    kStatusFieldNumber = 7,
    kPreferencesFieldNumber = 9,
    kPhoneFieldNumber = 10,
    kTelegramHandleFieldNumber = 11,
  };
  // repeated .myapp.Address addresses = 8;
  [[nodiscard]] int addresses_size()
      const;
  private:
  int _internal_addresses_size() const;

  public:
  void clear_addresses() ;
  [[nodiscard]] const ::myapp::Address& addresses(int index) const;
  [[nodiscard]] ::myapp::Address* PROTOBUF_NONNULL mutable_addresses(int index);
  ::myapp::Address* PROTOBUF_NONNULL add_addresses();
  [[nodiscard]] const ::google::protobuf::RepeatedPtrField<::myapp::Address>&
  addresses() const;
  [[nodiscard]] ::google::protobuf::RepeatedPtrField<::myapp::Address>* PROTOBUF_NONNULL
  mutable_addresses();

  private:
  const ::google::protobuf::RepeatedPtrField<::myapp::Address>& _internal_addresses() const;
  ::google::protobuf::RepeatedPtrField<::myapp::Address>* PROTOBUF_NONNULL _internal_mutable_addresses();

  public:
  // string name = 2;
  void clear_name() ;
  [[nodiscard]] const ::std::string& name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // string email = 3;
  void clear_email() ;
  [[nodiscard]] const ::std::string& email() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_email(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_email();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_email();
  void set_allocated_email(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_email() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_email(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_email();

  public:
  // bytes avatar = 6;
  void clear_avatar() ;
  [[nodiscard]] const ::std::string& avatar() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_avatar(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_avatar();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_avatar();
  void set_allocated_avatar(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_avatar() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_avatar(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_avatar();

  public:
  // int32 id = 1;
  void clear_id() ;
  [[nodiscard]] ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // bool is_verified = 4;
  void clear_is_verified() ;
  [[nodiscard]] bool is_verified() const;
  void set_is_verified(bool value);

  private:
  bool _internal_is_verified() const;
  void _internal_set_is_verified(bool value);

  public:
  // double balance = 5;
  void clear_balance() ;
  [[nodiscard]] double balance() const;
  void set_balance(double value);

  private:
  double _internal_balance() const;
  void _internal_set_balance(double value);

  public:
  // .myapp.User.Status status = 7;
  void clear_status() ;
  [[nodiscard]] ::myapp::User_Status status() const;
  void set_status(::myapp::User_Status value);

  private:
  ::myapp::User_Status _internal_status() const;
  void _internal_set_status(::myapp::User_Status value);

  public:
  // map<string, string> preferences = 9;
  [[nodiscard]] int preferences_size()
      const;
  private:
  int _internal_preferences_size() const;

  public:
  void clear_preferences() ;
  [[nodiscard]] const ::google::protobuf::Map<::std::string, ::std::string>& preferences() const;
  [[nodiscard]] ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL mutable_preferences();

  private:
  const ::google::protobuf::Map<::std::string, ::std::string>& _internal_preferences() const;
  ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL _internal_mutable_preferences();

  public:
  // string phone = 10;
  [[nodiscard]] bool has_phone()
      const;
  void clear_phone() ;
  [[nodiscard]] const ::std::string& phone() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_phone(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_phone();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_phone();
  void set_allocated_phone(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_phone() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_phone(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_phone();

  public:
  // string telegram_handle = 11;
  [[nodiscard]] bool has_telegram_handle()
      const;
  void clear_telegram_handle() ;
  [[nodiscard]] const ::std::string& telegram_handle() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_telegram_handle(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_telegram_handle();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_telegram_handle();
  void set_allocated_telegram_handle(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_telegram_handle() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_telegram_handle(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_telegram_handle();

  public:
  void clear_contact_method();
  ContactMethodCase contact_method_case() const;
  // @@protoc_insertion_point(class_scope:myapp.User)
 private:
  class _Internal;
  void set_has_phone();
  void set_has_telegram_handle();
  [[nodiscard]] inline bool has_contact_method() const;
  inline void clear_has_contact_method();
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<3, 11,
                          2, 67,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const User& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::myapp::Address > addresses_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::internal::ArenaStringPtr email_;
    ::google::protobuf::internal::ArenaStringPtr avatar_;
    ::int32_t id_;
    bool is_verified_;
    double balance_;
    int status_;
    ::google::protobuf::internal::MapField<User_PreferencesEntry_DoNotUse, ::std::string, ::std::string> preferences_;
    union ContactMethodUnion {
      constexpr ContactMethodUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::google::protobuf::internal::ArenaStringPtr phone_;
      ::google::protobuf::internal::ArenaStringPtr telegram_handle_;
    } contact_method_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_users_2fuser_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// User

// int32 id = 1;
inline void User::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
}
inline ::int32_t User::id() const {
  // @@protoc_insertion_point(field_get:myapp.User.id)
  return _internal_id();
}
inline void User::set_id(::int32_t value) {
  _internal_set_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:myapp.User.id)
}
inline ::int32_t User::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void User::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// string name = 2;
inline void User::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::std::string& User::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:myapp.User.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void User::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:myapp.User.name)
}
inline ::std::string* PROTOBUF_NONNULL User::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:myapp.User.name)
  return _s;
}
inline const ::std::string& User::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void User::_internal_set_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL User::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE User::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:myapp.User.name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void User::set_allocated_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:myapp.User.name)
}

// string email = 3;
inline void User::clear_email() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.email_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline const ::std::string& User::email() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:myapp.User.email)
  return _internal_email();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void User::set_email(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.email_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:myapp.User.email)
}
inline ::std::string* PROTOBUF_NONNULL User::mutable_email()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_email();
  // @@protoc_insertion_point(field_mutable:myapp.User.email)
  return _s;
}
inline const ::std::string& User::_internal_email() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.email_.Get();
}
inline void User::_internal_set_email(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.email_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL User::_internal_mutable_email() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.email_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE User::release_email() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:myapp.User.email)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.email_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.email_.Set("", GetArena());
  }
  return released;
}
inline void User::set_allocated_email(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.email_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.email_.IsDefault()) {
    _impl_.email_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:myapp.User.email)
}

// bool is_verified = 4;
inline void User::clear_is_verified() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_verified_ = false;
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
}
inline bool User::is_verified() const {
  // @@protoc_insertion_point(field_get:myapp.User.is_verified)
  return _internal_is_verified();
}
inline void User::set_is_verified(bool value) {
  _internal_set_is_verified(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:myapp.User.is_verified)
}
inline bool User::_internal_is_verified() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_verified_;
}
inline void User::_internal_set_is_verified(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_verified_ = value;
}

// double balance = 5;
inline void User::clear_balance() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.balance_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
}
inline double User::balance() const {
  // @@protoc_insertion_point(field_get:myapp.User.balance)
  return _internal_balance();
}
inline void User::set_balance(double value) {
  _internal_set_balance(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:myapp.User.balance)
}
inline double User::_internal_balance() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.balance_;
}
inline void User::_internal_set_balance(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.balance_ = value;
}

// bytes avatar = 6;
inline void User::clear_avatar() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.avatar_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline const ::std::string& User::avatar() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:myapp.User.avatar)
  return _internal_avatar();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void User::set_avatar(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.avatar_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:myapp.User.avatar)
}
inline ::std::string* PROTOBUF_NONNULL User::mutable_avatar()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_avatar();
  // @@protoc_insertion_point(field_mutable:myapp.User.avatar)
  return _s;
}
inline const ::std::string& User::_internal_avatar() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.avatar_.Get();
}
inline void User::_internal_set_avatar(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.avatar_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL User::_internal_mutable_avatar() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.avatar_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE User::release_avatar() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:myapp.User.avatar)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.avatar_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.avatar_.Set("", GetArena());
  }
  return released;
}
inline void User::set_allocated_avatar(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.avatar_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.avatar_.IsDefault()) {
    _impl_.avatar_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:myapp.User.avatar)
}

// .myapp.User.Status status = 7;
inline void User::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000080U);
}
inline ::myapp::User_Status User::status() const {
  // @@protoc_insertion_point(field_get:myapp.User.status)
  return _internal_status();
}
inline void User::set_status(::myapp::User_Status value) {
  _internal_set_status(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:myapp.User.status)
}
inline ::myapp::User_Status User::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::myapp::User_Status>(_impl_.status_);
}
inline void User::_internal_set_status(::myapp::User_Status value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// repeated .myapp.Address addresses = 8;
inline int User::_internal_addresses_size() const {
  return _internal_addresses().size();
}
inline int User::addresses_size() const {
  return _internal_addresses_size();
}
inline const ::myapp::Address& User::addresses(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:myapp.User.addresses)
  return _internal_addresses().Get(index);
}
inline ::myapp::Address* PROTOBUF_NONNULL User::mutable_addresses(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:myapp.User.addresses)
  return _internal_mutable_addresses()->Mutable(index);
}
inline ::myapp::Address* PROTOBUF_NONNULL User::add_addresses()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::myapp::Address* _add =
      _internal_mutable_addresses()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:myapp.User.addresses)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::myapp::Address>& User::addresses() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:myapp.User.addresses)
  return _internal_addresses();
}
inline ::google::protobuf::RepeatedPtrField<::myapp::Address>* PROTOBUF_NONNULL
User::mutable_addresses() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:myapp.User.addresses)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_addresses();
}
inline const ::google::protobuf::RepeatedPtrField<::myapp::Address>&
User::_internal_addresses() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.addresses_;
}
inline ::google::protobuf::RepeatedPtrField<::myapp::Address>* PROTOBUF_NONNULL
User::_internal_mutable_addresses() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.addresses_;
}

// map<string, string> preferences = 9;
inline int User::_internal_preferences_size() const {
  return _internal_preferences().size();
}
inline int User::preferences_size() const {
  return _internal_preferences_size();
}
inline void User::clear_preferences() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.preferences_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000100U);
}
inline const ::google::protobuf::Map<::std::string, ::std::string>& User::_internal_preferences() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.preferences_.GetMap();
}
inline const ::google::protobuf::Map<::std::string, ::std::string>& User::preferences() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:myapp.User.preferences)
  return _internal_preferences();
}
inline ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL User::_internal_mutable_preferences() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.preferences_.MutableMap();
}
inline ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL User::mutable_preferences()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_mutable_map:myapp.User.preferences)
  return _internal_mutable_preferences();
}

// string phone = 10;
inline bool User::has_phone() const {
  return contact_method_case() == kPhone;
}
inline void User::set_has_phone() {
  _impl_._oneof_case_[0] = kPhone;
}
inline void User::clear_phone() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (contact_method_case() == kPhone) {
    _impl_.contact_method_.phone_.Destroy();
    clear_has_contact_method();
  }
}
inline const ::std::string& User::phone() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:myapp.User.phone)
  return _internal_phone();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void User::set_phone(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (contact_method_case() != kPhone) {
    clear_contact_method();

    set_has_phone();
    _impl_.contact_method_.phone_.InitDefault();
  }
  _impl_.contact_method_.phone_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:myapp.User.phone)
}
inline ::std::string* PROTOBUF_NONNULL User::mutable_phone()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  if (contact_method_case() != kPhone) {
    clear_contact_method();

    set_has_phone();
    _impl_.contact_method_.phone_.InitDefault();
  }
  ::std::string* _s = _internal_mutable_phone();
  // @@protoc_insertion_point(field_mutable:myapp.User.phone)
  return _s;
}
inline const ::std::string& User::_internal_phone() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  if (contact_method_case() != kPhone) {
    return ::google::protobuf::internal::GetEmptyStringAlreadyInited();
  }
  return _impl_.contact_method_.phone_.Get();
}
inline void User::_internal_set_phone(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.contact_method_.phone_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL User::_internal_mutable_phone() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.contact_method_.phone_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE User::release_phone() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:myapp.User.phone)
  if (contact_method_case() != kPhone) {
    return nullptr;
  }
  clear_has_contact_method();
  return _impl_.contact_method_.phone_.Release();
}
inline void User::set_allocated_phone(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (has_contact_method()) {
    clear_contact_method();
  }
  if (value != nullptr) {
    set_has_phone();
    _impl_.contact_method_.phone_.InitAllocated(value, GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:myapp.User.phone)
}

// string telegram_handle = 11;
inline bool User::has_telegram_handle() const {
  return contact_method_case() == kTelegramHandle;
}
inline void User::set_has_telegram_handle() {
  _impl_._oneof_case_[0] = kTelegramHandle;
}
inline void User::clear_telegram_handle() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (contact_method_case() == kTelegramHandle) {
    _impl_.contact_method_.telegram_handle_.Destroy();
    clear_has_contact_method();
  }
}
inline const ::std::string& User::telegram_handle() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:myapp.User.telegram_handle)
  return _internal_telegram_handle();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void User::set_telegram_handle(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (contact_method_case() != kTelegramHandle) {
    clear_contact_method();

    set_has_telegram_handle();
    _impl_.contact_method_.telegram_handle_.InitDefault();
  }
  _impl_.contact_method_.telegram_handle_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:myapp.User.telegram_handle)
}
inline ::std::string* PROTOBUF_NONNULL User::mutable_telegram_handle()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  if (contact_method_case() != kTelegramHandle) {
    clear_contact_method();

    set_has_telegram_handle();
    _impl_.contact_method_.telegram_handle_.InitDefault();
  }
  ::std::string* _s = _internal_mutable_telegram_handle();
  // @@protoc_insertion_point(field_mutable:myapp.User.telegram_handle)
  return _s;
}
inline const ::std::string& User::_internal_telegram_handle() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  if (contact_method_case() != kTelegramHandle) {
    return ::google::protobuf::internal::GetEmptyStringAlreadyInited();
  }
  return _impl_.contact_method_.telegram_handle_.Get();
}
inline void User::_internal_set_telegram_handle(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.contact_method_.telegram_handle_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL User::_internal_mutable_telegram_handle() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.contact_method_.telegram_handle_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE User::release_telegram_handle() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:myapp.User.telegram_handle)
  if (contact_method_case() != kTelegramHandle) {
    return nullptr;
  }
  clear_has_contact_method();
  return _impl_.contact_method_.telegram_handle_.Release();
}
inline void User::set_allocated_telegram_handle(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (has_contact_method()) {
    clear_contact_method();
  }
  if (value != nullptr) {
    set_has_telegram_handle();
    _impl_.contact_method_.telegram_handle_.InitAllocated(value, GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:myapp.User.telegram_handle)
}

inline bool User::has_contact_method() const {
  return contact_method_case() != CONTACT_METHOD_NOT_SET;
}
inline void User::clear_has_contact_method() {
  _impl_._oneof_case_[0] = CONTACT_METHOD_NOT_SET;
}
inline User::ContactMethodCase User::contact_method_case() const {
  return User::ContactMethodCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace myapp


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::myapp::User_Status> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::myapp::User_Status>() {
  return ::myapp::User_Status_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // users_2fuser_2eproto_2epb_2eh
