// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: users/user.proto
// Protobuf C++ Version: 7.35.1

#include "users/user.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::myapp::User_PreferencesEntry_DoNotUse
        {&::_pbi::kDescriptorMethods, &::descriptor_table_users_2fuser_2eproto, /* tracker*/ nullptr,},
        // ::myapp::User
        {&::_pbi::kDescriptorMethods, &::descriptor_table_users_2fuser_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
namespace myapp {
constexpr User_PreferencesEntry_DoNotUse::ParseTableT_ User_PreferencesEntry_DoNotUse::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(User_PreferencesEntry_DoNotUse, _impl_._has_bits_),
      0, // no _extensions_
      2, 8,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967292,  // skipmap
      offsetof(ParseTableT_, field_entries),
      2,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::myapp::User_PreferencesEntry_DoNotUse>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // string value = 2;
      {::_pbi::TcParser::FastUS1,
       {18, 1, 0,
        PROTOBUF_FIELD_OFFSET(User_PreferencesEntry_DoNotUse, _impl_.value_)}},
      // string key = 1;
      {::_pbi::TcParser::FastUS1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(User_PreferencesEntry_DoNotUse, _impl_.key_)}},
    }}, {{
      65535, 65535
    }}, {{
      // string key = 1;
      {PROTOBUF_FIELD_OFFSET(User_PreferencesEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // string value = 2;
      {PROTOBUF_FIELD_OFFSET(User_PreferencesEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    }},
    // no aux_entries
    {{
      "\33\3\5\0\0\0\0\0"
      "myapp.User.PreferencesEntry"
      "key"
      "value"
    }},
  };
}

template <typename>
constexpr User_PreferencesEntry_DoNotUse::User_PreferencesEntry_DoNotUse(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : User_PreferencesEntry_DoNotUse::MapEntry(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
      ) {
}
inline void* PROTOBUF_NONNULL User_PreferencesEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) User_PreferencesEntry_DoNotUse(arena);
}
constexpr auto User_PreferencesEntry_DoNotUse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(User_PreferencesEntry_DoNotUse), alignof(User_PreferencesEntry_DoNotUse));
}
constexpr auto User_PreferencesEntry_DoNotUse::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &User_PreferencesEntry_DoNotUse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<User_PreferencesEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &User_PreferencesEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&User_PreferencesEntry_DoNotUse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(User_PreferencesEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_users_2fuser_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct User_PreferencesEntry_DoNotUseGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr User_PreferencesEntry_DoNotUseGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 User_PreferencesEntry_DoNotUse_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(User_PreferencesEntry_DoNotUse::InternalGenerateClassData_(
            _default, &User_PreferencesEntry_DoNotUse_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<User_PreferencesEntry_DoNotUse>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~User_PreferencesEntry_DoNotUseGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) User_PreferencesEntry_DoNotUse _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<User_PreferencesEntry_DoNotUse>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(User_PreferencesEntry_DoNotUseGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST User_PreferencesEntry_DoNotUseGlobalsTypeInternal User_PreferencesEntry_DoNotUse_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* User_PreferencesEntry_DoNotUse_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return User_PreferencesEntry_DoNotUse_globals_.GetClassData();
#else
  return User_PreferencesEntry_DoNotUse_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class User::_Internal {
 public:
  using HasBits = decltype(::std::declval<User>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(User, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::myapp::User, _impl_._oneof_case_);
};

constexpr User::ParseTableT_ User::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(User, _impl_._has_bits_),
      0, // no _extensions_
      11, 56,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294965248,  // skipmap
      offsetof(ParseTableT_, field_entries),
      11,  // num_field_entries
      2,  // num_aux_entries
      offsetof(ParseTableT_, aux_entries),
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::myapp::User>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // repeated .myapp.Address addresses = 8;
      {::_pbi::TcParser::FastMtR1,
       {66, 0, 0,
        PROTOBUF_FIELD_OFFSET(User, _impl_.addresses_)}},
      // int32 id = 1;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(User, _impl_.id_), 4>(),
       {8, 4, 0,
        PROTOBUF_FIELD_OFFSET(User, _impl_.id_)}},
      // string name = 2;
      {::_pbi::TcParser::FastUS1,
       {18, 1, 0,
        PROTOBUF_FIELD_OFFSET(User, _impl_.name_)}},
      // string email = 3;
      {::_pbi::TcParser::FastUS1,
       {26, 2, 0,
        PROTOBUF_FIELD_OFFSET(User, _impl_.email_)}},
      // bool is_verified = 4;
      {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(User, _impl_.is_verified_), 5>(),
       {32, 5, 0,
        PROTOBUF_FIELD_OFFSET(User, _impl_.is_verified_)}},
      // double balance = 5;
      {::_pbi::TcParser::FastF64S1,
       {41, 6, 0,
        PROTOBUF_FIELD_OFFSET(User, _impl_.balance_)}},
      // bytes avatar = 6;
      {::_pbi::TcParser::FastBS1,
       {50, 3, 0,
        PROTOBUF_FIELD_OFFSET(User, _impl_.avatar_)}},
      // .myapp.User.Status status = 7;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(User, _impl_.status_), 7>(),
       {56, 7, 0,
        PROTOBUF_FIELD_OFFSET(User, _impl_.status_)}},
    }}, {{
      65535, 65535
    }}, {{
      // int32 id = 1;
      {PROTOBUF_FIELD_OFFSET(User, _impl_.id_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
      // string name = 2;
      {PROTOBUF_FIELD_OFFSET(User, _impl_.name_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // string email = 3;
      {PROTOBUF_FIELD_OFFSET(User, _impl_.email_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // bool is_verified = 4;
      {PROTOBUF_FIELD_OFFSET(User, _impl_.is_verified_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
      // double balance = 5;
      {PROTOBUF_FIELD_OFFSET(User, _impl_.balance_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
      // bytes avatar = 6;
      {PROTOBUF_FIELD_OFFSET(User, _impl_.avatar_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
      // .myapp.User.Status status = 7;
      {PROTOBUF_FIELD_OFFSET(User, _impl_.status_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
      // repeated .myapp.Address addresses = 8;
      {PROTOBUF_FIELD_OFFSET(User, _impl_.addresses_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
      // map<string, string> preferences = 9;
      {PROTOBUF_FIELD_OFFSET(User, _impl_.preferences_), _Internal::kHasBitsOffset + 8, 1, (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
      // string phone = 10;
      {PROTOBUF_FIELD_OFFSET(User, _impl_.contact_method_.phone_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // string telegram_handle = 11;
      {PROTOBUF_FIELD_OFFSET(User, _impl_.contact_method_.telegram_handle_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kUtf8String | ::_fl::kRepAString)},
    }},
    {{
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::myapp::Address>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::myapp::Address_globals_},
        #endif
        {::_pbi::TcParser::GetMapAuxInfo(
            1, 0, 9, 9, 0)},
    }},
    {{
      "\12\0\4\5\0\0\0\0\0\13\5\17\0\0\0\0"
      "myapp.User"
      "name"
      "email"
      "preferences"
      "phone"
      "telegram_handle"
    }},
  };
}


inline constexpr User::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        addresses_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::myapp::User,
            PROTOBUF_FIELD_OFFSET(::myapp::User, _impl_.addresses_)>()
         }
        ,
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        email_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        avatar_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0},
        is_verified_{false},
        balance_{0},
        status_{static_cast< ::myapp::User_Status >(0)},
        preferences_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::myapp::User,
            PROTOBUF_FIELD_OFFSET(::myapp::User, _impl_.preferences_)>()
         }
        ,
        contact_method_{},
        _oneof_case_{} {}

template <typename>
constexpr User::User(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL User::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) User(arena);
}
constexpr auto User::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(User), alignof(User));
}
constexpr auto User::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &User::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<User>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &User::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<User>(), &User::ByteSizeLong,
              &User::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(User, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[1],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_users_2fuser_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct UserGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr UserGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 User_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(User::InternalGenerateClassData_(
            _default, &User_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<User>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~UserGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) User _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<User>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(UserGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST UserGlobalsTypeInternal User_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* User_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return User_globals_.GetClassData();
#else
  return User_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace myapp
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_users_2fuser_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_users_2fuser_2eproto = nullptr;
const ::uint32_t
    TableStruct_users_2fuser_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::myapp::User_PreferencesEntry_DoNotUse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::myapp::User_PreferencesEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::myapp::User_PreferencesEntry_DoNotUse, _impl_.value_),
        0,
        1,
        0x085, // bitmap
        PROTOBUF_FIELD_OFFSET(::myapp::User, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::myapp::User, _impl_._oneof_case_[0]),
        16, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::myapp::User, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::myapp::User, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::myapp::User, _impl_.email_),
        PROTOBUF_FIELD_OFFSET(::myapp::User, _impl_.is_verified_),
        PROTOBUF_FIELD_OFFSET(::myapp::User, _impl_.balance_),
        PROTOBUF_FIELD_OFFSET(::myapp::User, _impl_.avatar_),
        PROTOBUF_FIELD_OFFSET(::myapp::User, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::myapp::User, _impl_.addresses_),
        PROTOBUF_FIELD_OFFSET(::myapp::User, _impl_.preferences_),
        PROTOBUF_FIELD_OFFSET(::myapp::User, _impl_.contact_method_),
        PROTOBUF_FIELD_OFFSET(::myapp::User, _impl_.contact_method_),
        PROTOBUF_FIELD_OFFSET(::myapp::User, _impl_.contact_method_),
        4,
        1,
        2,
        5,
        6,
        3,
        7,
        0,
        8,
        ~0u,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::myapp::User_PreferencesEntry_DoNotUse)},
        {7, sizeof(::myapp::User)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::myapp::User_PreferencesEntry_DoNotUse_globals_,
        &::myapp::User_globals_,
};
const char descriptor_table_protodef_users_2fuser_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020users/user.proto\022\005myapp\032\024common/addres"
    "s.proto\"\252\003\n\004User\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001"
    "(\t\022\r\n\005email\030\003 \001(\t\022\023\n\013is_verified\030\004 \001(\010\022\017"
    "\n\007balance\030\005 \001(\001\022\016\n\006avatar\030\006 \001(\014\022\"\n\006statu"
    "s\030\007 \001(\0162\022.myapp.User.Status\022!\n\taddresses"
    "\030\010 \003(\0132\016.myapp.Address\0221\n\013preferences\030\t "
    "\003(\0132\034.myapp.User.PreferencesEntry\022\017\n\005pho"
    "ne\030\n \001(\tH\000\022\031\n\017telegram_handle\030\013 \001(\tH\000\0322\n"
    "\020PreferencesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030"
    "\002 \001(\t:\0028\001\"W\n\006Status\022\022\n\016STATUS_UNKNOWN\020\000\022"
    "\021\n\rSTATUS_ACTIVE\020\001\022\022\n\016STATUS_SUSPEND\020\002\022\022"
    "\n\016STATUS_DELETED\020\003B\020\n\016contact_methodB\002H\001"
    "b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_users_2fuser_2eproto_deps[1] = {
        &::descriptor_table_common_2faddress_2eproto,
};
static ::absl::once_flag descriptor_table_users_2fuser_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_users_2fuser_2eproto = {
    false,
    false,
    488,
    descriptor_table_protodef_users_2fuser_2eproto,
    "users/user.proto",
    &descriptor_table_users_2fuser_2eproto_once,
    descriptor_table_users_2fuser_2eproto_deps,
    1,
    2,
    schemas,
    file_message_globals,
    TableStruct_users_2fuser_2eproto::offsets,
    file_level_enum_descriptors_users_2fuser_2eproto,
    file_level_service_descriptors_users_2fuser_2eproto,
};
namespace myapp {
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
User_Status_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_users_2fuser_2eproto);
  return file_level_enum_descriptors_users_2fuser_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t User_Status_internal_data_[] = {
    262144u, 0u, };
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
User_PreferencesEntry_DoNotUse::User_PreferencesEntry_DoNotUse() : SuperType(User_PreferencesEntry_DoNotUse_get_class_data()) {}
User_PreferencesEntry_DoNotUse::User_PreferencesEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : SuperType(arena, User_PreferencesEntry_DoNotUse_get_class_data()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
User_PreferencesEntry_DoNotUse::User_PreferencesEntry_DoNotUse() : SuperType() {}
User_PreferencesEntry_DoNotUse::User_PreferencesEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull User_PreferencesEntry_DoNotUse_class_data_ =
        User_PreferencesEntry_DoNotUse::InternalGenerateClassData_(User_PreferencesEntry_DoNotUse_globals_._default);

// including ~ all the vtables and everything they use become part
// of the same ~ SCC.
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
User_PreferencesEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&User_PreferencesEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(User_PreferencesEntry_DoNotUse_class_data_.tc_table);
  return User_PreferencesEntry_DoNotUse_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
User_PreferencesEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&User_PreferencesEntry_DoNotUse_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&User_PreferencesEntry_DoNotUse_globals_));
  return User_PreferencesEntry_DoNotUse_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const User_PreferencesEntry_DoNotUse::ParseTableT_
    User_PreferencesEntry_DoNotUse::_table_ =
        User_PreferencesEntry_DoNotUse::InternalGenerateParseTable_(User_PreferencesEntry_DoNotUse_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
// ===================================================================

void User::clear_addresses() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.addresses_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
User::User(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, User_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:myapp.User)
}
PROTOBUF_NDEBUG_INLINE User::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::myapp::User& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        addresses_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::myapp::User,
              PROTOBUF_FIELD_OFFSET(::myapp::User, _impl_.addresses_)>()
          , from.addresses_
        }
        ,
        name_(arena, from.name_),
        email_(arena, from.email_),
        avatar_(arena, from.avatar_),
        preferences_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::myapp::User,
              PROTOBUF_FIELD_OFFSET(::myapp::User, _impl_.preferences_)>()
          , from.preferences_
        }
        ,
        contact_method_{},
        _oneof_case_{from._oneof_case_[0]} {}

User::User(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const User& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, User_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  User* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, status_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::status_));
  switch (contact_method_case()) {
    case CONTACT_METHOD_NOT_SET:
      break;
      case kPhone:
        new (&_impl_.contact_method_.phone_) decltype(_impl_.contact_method_.phone_){arena, from._impl_.contact_method_.phone_};
        break;
      case kTelegramHandle:
        new (&_impl_.contact_method_.telegram_handle_) decltype(_impl_.contact_method_.telegram_handle_){arena, from._impl_.contact_method_.telegram_handle_};
        break;
  }

  // @@protoc_insertion_point(copy_constructor:myapp.User)
}
PROTOBUF_NDEBUG_INLINE User::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        addresses_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::myapp::User,
            PROTOBUF_FIELD_OFFSET(::myapp::User, _impl_.addresses_)>()
         }
        ,
        name_(arena),
        email_(arena),
        avatar_(arena),
        preferences_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::myapp::User,
            PROTOBUF_FIELD_OFFSET(::myapp::User, _impl_.preferences_)>()
         }
        ,
        contact_method_{},
        _oneof_case_{} {}

inline void User::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, status_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::status_));
}
User::~User() {
  // @@protoc_insertion_point(destructor:myapp.User)
  SharedDtor(*this);
}
inline void User::SharedDtor(MessageLite& self) {
  User& this_ = static_cast<User&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.email_.Destroy();
  this_._impl_.avatar_.Destroy();
  if (this_.has_contact_method()) {
    this_.clear_contact_method();
  }
  this_._impl_.~Impl_();
}

void User::clear_contact_method() {
// @@protoc_insertion_point(one_of_clear_start:myapp.User)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (contact_method_case()) {
    case kPhone: {
      _impl_.contact_method_.phone_.Destroy();
      break;
    }
    case kTelegramHandle: {
      _impl_.contact_method_.telegram_handle_.Destroy();
      break;
    }
    case CONTACT_METHOD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = CONTACT_METHOD_NOT_SET;
}


#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull User_class_data_ =
        User::InternalGenerateClassData_(User_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
User::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&User_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(User_class_data_.tc_table);
  return User_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
User::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&User_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&User_globals_));
  return User_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const User::ParseTableT_
    User::_table_ =
        User::InternalGenerateParseTable_(User_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void User::Clear() {
// @@protoc_insertion_point(message_clear_start:myapp.User)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.addresses_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.email_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.avatar_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000f0U)) {
    ::memset(&_impl_.id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.status_) -
        reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.status_));
  }
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    _impl_.preferences_.Clear();
  }
  clear_contact_method();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL User::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const User& this_ = static_cast<const User&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL User::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const User& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:myapp.User)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_id(), target);
    }
  }

  // string name = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_name().empty()) {
      const ::std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "myapp.User.name");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string email = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_email().empty()) {
      const ::std::string& _s = this_._internal_email();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "myapp.User.email");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // bool is_verified = 4;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_is_verified() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          4, this_._internal_is_verified(), target);
    }
  }

  // double balance = 5;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_balance()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          5, this_._internal_balance(), target);
    }
  }

  // bytes avatar = 6;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_avatar().empty()) {
      const ::std::string& _s = this_._internal_avatar();
      target = stream->WriteBytesMaybeAliased(6, _s, target);
    }
  }

  // .myapp.User.Status status = 7;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (this_._internal_status() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          7, this_._internal_status(), target);
    }
  }

  // repeated .myapp.Address addresses = 8;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_addresses_size());
         i < n; i++) {
      const auto& repfield = this_._internal_addresses().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              8, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // map<string, string> preferences = 9;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    if (!this_._internal_preferences().empty()) {
      using MapType = ::google::protobuf::Map<::std::string, ::std::string>;
      using WireHelper = _pbi::MapEntryFuncs<::std::string, ::std::string,
                                     _pbi::WireFormatLite::TYPE_STRING,
                                     _pbi::WireFormatLite::TYPE_STRING>;
      const auto& field = this_._internal_preferences();

      if (stream->IsSerializationDeterministic() && field.size() > 1) {
        for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
          target = WireHelper::InternalSerialize(
              9, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "myapp.User.preferences");
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "myapp.User.preferences");
        }
      } else {
        for (const auto& entry : field) {
          target = WireHelper::InternalSerialize(
              9, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "myapp.User.preferences");
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "myapp.User.preferences");
        }
      }
    }
  }

  switch (this_.contact_method_case()) {
    case kPhone: {
      const ::std::string& _s = this_._internal_phone();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "myapp.User.phone");
      target = stream->WriteStringMaybeAliased(10, _s, target);
      break;
    }
    case kTelegramHandle: {
      const ::std::string& _s = this_._internal_telegram_handle();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "myapp.User.telegram_handle");
      target = stream->WriteStringMaybeAliased(11, _s, target);
      break;
    }
    default:
      break;
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:myapp.User)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t User::ByteSizeLong(const MessageLite& base) {
  const User& this_ = static_cast<const User&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t User::ByteSizeLong() const {
  const User& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:myapp.User)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // repeated .myapp.Address addresses = 8;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_addresses_size();
      for (const auto& msg : this_._internal_addresses()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // string name = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_name());
      }
    }
    // string email = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_email().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_email());
      }
    }
    // bytes avatar = 6;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_avatar().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_avatar());
      }
    }
    // int32 id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_id());
      }
    }
    // bool is_verified = 4;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_is_verified() != 0) {
        total_size += 2;
      }
    }
    // double balance = 5;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_balance()) != 0) {
        total_size += 9;
      }
    }
    // .myapp.User.Status status = 7;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (this_._internal_status() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
      }
    }
  }
   {
    // map<string, string> preferences = 9;
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_preferences_size());
      for (const auto& entry : this_._internal_preferences()) {
        total_size += _pbi::MapEntryFuncs<::std::string, ::std::string,
                                       _pbi::WireFormatLite::TYPE_STRING,
                                       _pbi::WireFormatLite::TYPE_STRING>::ByteSizeLong(entry.first, entry.second);
      }
    }
  }
  switch (this_.contact_method_case()) {
    // string phone = 10;
    case kPhone: {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_phone());
      break;
    }
    // string telegram_handle = 11;
    case kTelegramHandle: {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_telegram_handle());
      break;
    }
    case CONTACT_METHOD_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void User::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<User*>(&to_msg);
  auto& from = static_cast<const User&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:myapp.User)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_addresses()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_addresses());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_name().empty()) {
        _this->_internal_set_name(from._internal_name());
      } else {
        if (_this->_impl_.name_.IsDefault()) {
          _this->_internal_set_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_email().empty()) {
        _this->_internal_set_email(from._internal_email());
      } else {
        if (_this->_impl_.email_.IsDefault()) {
          _this->_internal_set_email("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_avatar().empty()) {
        _this->_internal_set_avatar(from._internal_avatar());
      } else {
        if (_this->_impl_.avatar_.IsDefault()) {
          _this->_internal_set_avatar("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_id() != 0) {
        _this->_impl_.id_ = from._impl_.id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_is_verified() != 0) {
        _this->_impl_.is_verified_ = from._impl_.is_verified_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_balance()) != 0) {
        _this->_impl_.balance_ = from._impl_.balance_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (from._internal_status() != 0) {
        _this->_impl_.status_ = from._impl_.status_;
      }
    }
  }
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    _this->_impl_.preferences_.MergeFrom(from._impl_.preferences_);
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  if (const uint32_t oneof_from_case =
          from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_contact_method();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kPhone: {
        if (oneof_needs_init) {
          _this->_impl_.contact_method_.phone_.InitDefault();
        }
        _this->_impl_.contact_method_.phone_.Set(from._internal_phone(), arena);
        break;
      }
      case kTelegramHandle: {
        if (oneof_needs_init) {
          _this->_impl_.contact_method_.telegram_handle_.InitDefault();
        }
        _this->_impl_.contact_method_.telegram_handle_.Set(from._internal_telegram_handle(), arena);
        break;
      }
      case CONTACT_METHOD_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void User::CopyFrom(const User& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:myapp.User)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void User::InternalSwap(User* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.addresses_.InternalSwap(&other->_impl_.addresses_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.email_, &other->_impl_.email_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.avatar_, &other->_impl_.avatar_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(User, _impl_.status_)
      + sizeof(User::_impl_.status_)
      - PROTOBUF_FIELD_OFFSET(User, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
  _impl_.preferences_.InternalSwap(&other->_impl_.preferences_);
  swap(_impl_.contact_method_, other->_impl_.contact_method_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata User::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace myapp
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_users_2fuser_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
