// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: order_service.proto
#ifndef GRPC_order_5fservice_2eproto__INCLUDED
#define GRPC_order_5fservice_2eproto__INCLUDED

#include "order_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace myapp {

class OrderService final {
 public:
  static constexpr char const* service_full_name() {
    return "myapp.OrderService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 1. Unary — один запрос, один ответ. Самый частый вид RPC,
    //    ведёт себя как обычный вызов функции по сети.
    virtual ::grpc::Status GetOrder(::grpc::ClientContext* context, const ::myapp::OrderRequest& request, ::myapp::OrderResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::myapp::OrderResponse>> AsyncGetOrder(::grpc::ClientContext* context, const ::myapp::OrderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::myapp::OrderResponse>>(AsyncGetOrderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::myapp::OrderResponse>> PrepareAsyncGetOrder(::grpc::ClientContext* context, const ::myapp::OrderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::myapp::OrderResponse>>(PrepareAsyncGetOrderRaw(context, request, cq));
    }
    // 2. Server streaming — один запрос, СЕРВЕР шлёт поток ответов.
    //    Клиент запросил один раз, сервер отдаёт данные порциями
    //    (например, историю статусов заказа).
    std::unique_ptr< ::grpc::ClientReaderInterface< ::myapp::OrderResponse>> WatchOrderStatus(::grpc::ClientContext* context, const ::myapp::OrderRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::myapp::OrderResponse>>(WatchOrderStatusRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::myapp::OrderResponse>> AsyncWatchOrderStatus(::grpc::ClientContext* context, const ::myapp::OrderRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::myapp::OrderResponse>>(AsyncWatchOrderStatusRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::myapp::OrderResponse>> PrepareAsyncWatchOrderStatus(::grpc::ClientContext* context, const ::myapp::OrderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::myapp::OrderResponse>>(PrepareAsyncWatchOrderStatusRaw(context, request, cq));
    }
    // 3. Client streaming — КЛИЕНТ шлёт поток запросов, сервер отвечает один раз
    //    в конце (например, серия обновлений полей заказа, применяются пачкой).
    std::unique_ptr< ::grpc::ClientWriterInterface< ::myapp::OrderUpdate>> BatchUpdateOrder(::grpc::ClientContext* context, ::myapp::Ack* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::myapp::OrderUpdate>>(BatchUpdateOrderRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::myapp::OrderUpdate>> AsyncBatchUpdateOrder(::grpc::ClientContext* context, ::myapp::Ack* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::myapp::OrderUpdate>>(AsyncBatchUpdateOrderRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::myapp::OrderUpdate>> PrepareAsyncBatchUpdateOrder(::grpc::ClientContext* context, ::myapp::Ack* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::myapp::OrderUpdate>>(PrepareAsyncBatchUpdateOrderRaw(context, response, cq));
    }
    // 4. Bidi (двунаправленный) streaming — оба потока независимы,
    //    клиент и сервер шлют сообщения в любом порядке по одному соединению.
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::myapp::OrderUpdate, ::myapp::OrderResponse>> SyncOrders(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::myapp::OrderUpdate, ::myapp::OrderResponse>>(SyncOrdersRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::myapp::OrderUpdate, ::myapp::OrderResponse>> AsyncSyncOrders(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::myapp::OrderUpdate, ::myapp::OrderResponse>>(AsyncSyncOrdersRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::myapp::OrderUpdate, ::myapp::OrderResponse>> PrepareAsyncSyncOrders(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::myapp::OrderUpdate, ::myapp::OrderResponse>>(PrepareAsyncSyncOrdersRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 1. Unary — один запрос, один ответ. Самый частый вид RPC,
      //    ведёт себя как обычный вызов функции по сети.
      virtual void GetOrder(::grpc::ClientContext* context, const ::myapp::OrderRequest* request, ::myapp::OrderResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetOrder(::grpc::ClientContext* context, const ::myapp::OrderRequest* request, ::myapp::OrderResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 2. Server streaming — один запрос, СЕРВЕР шлёт поток ответов.
      //    Клиент запросил один раз, сервер отдаёт данные порциями
      //    (например, историю статусов заказа).
      virtual void WatchOrderStatus(::grpc::ClientContext* context, const ::myapp::OrderRequest* request, ::grpc::ClientReadReactor< ::myapp::OrderResponse>* reactor) = 0;
      // 3. Client streaming — КЛИЕНТ шлёт поток запросов, сервер отвечает один раз
      //    в конце (например, серия обновлений полей заказа, применяются пачкой).
      virtual void BatchUpdateOrder(::grpc::ClientContext* context, ::myapp::Ack* response, ::grpc::ClientWriteReactor< ::myapp::OrderUpdate>* reactor) = 0;
      // 4. Bidi (двунаправленный) streaming — оба потока независимы,
      //    клиент и сервер шлют сообщения в любом порядке по одному соединению.
      virtual void SyncOrders(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::myapp::OrderUpdate,::myapp::OrderResponse>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::myapp::OrderResponse>* AsyncGetOrderRaw(::grpc::ClientContext* context, const ::myapp::OrderRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::myapp::OrderResponse>* PrepareAsyncGetOrderRaw(::grpc::ClientContext* context, const ::myapp::OrderRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::myapp::OrderResponse>* WatchOrderStatusRaw(::grpc::ClientContext* context, const ::myapp::OrderRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::myapp::OrderResponse>* AsyncWatchOrderStatusRaw(::grpc::ClientContext* context, const ::myapp::OrderRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::myapp::OrderResponse>* PrepareAsyncWatchOrderStatusRaw(::grpc::ClientContext* context, const ::myapp::OrderRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientWriterInterface< ::myapp::OrderUpdate>* BatchUpdateOrderRaw(::grpc::ClientContext* context, ::myapp::Ack* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::myapp::OrderUpdate>* AsyncBatchUpdateOrderRaw(::grpc::ClientContext* context, ::myapp::Ack* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::myapp::OrderUpdate>* PrepareAsyncBatchUpdateOrderRaw(::grpc::ClientContext* context, ::myapp::Ack* response, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::myapp::OrderUpdate, ::myapp::OrderResponse>* SyncOrdersRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::myapp::OrderUpdate, ::myapp::OrderResponse>* AsyncSyncOrdersRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::myapp::OrderUpdate, ::myapp::OrderResponse>* PrepareAsyncSyncOrdersRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetOrder(::grpc::ClientContext* context, const ::myapp::OrderRequest& request, ::myapp::OrderResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::myapp::OrderResponse>> AsyncGetOrder(::grpc::ClientContext* context, const ::myapp::OrderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::myapp::OrderResponse>>(AsyncGetOrderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::myapp::OrderResponse>> PrepareAsyncGetOrder(::grpc::ClientContext* context, const ::myapp::OrderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::myapp::OrderResponse>>(PrepareAsyncGetOrderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::myapp::OrderResponse>> WatchOrderStatus(::grpc::ClientContext* context, const ::myapp::OrderRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::myapp::OrderResponse>>(WatchOrderStatusRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::myapp::OrderResponse>> AsyncWatchOrderStatus(::grpc::ClientContext* context, const ::myapp::OrderRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::myapp::OrderResponse>>(AsyncWatchOrderStatusRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::myapp::OrderResponse>> PrepareAsyncWatchOrderStatus(::grpc::ClientContext* context, const ::myapp::OrderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::myapp::OrderResponse>>(PrepareAsyncWatchOrderStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriter< ::myapp::OrderUpdate>> BatchUpdateOrder(::grpc::ClientContext* context, ::myapp::Ack* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::myapp::OrderUpdate>>(BatchUpdateOrderRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::myapp::OrderUpdate>> AsyncBatchUpdateOrder(::grpc::ClientContext* context, ::myapp::Ack* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::myapp::OrderUpdate>>(AsyncBatchUpdateOrderRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::myapp::OrderUpdate>> PrepareAsyncBatchUpdateOrder(::grpc::ClientContext* context, ::myapp::Ack* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::myapp::OrderUpdate>>(PrepareAsyncBatchUpdateOrderRaw(context, response, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::myapp::OrderUpdate, ::myapp::OrderResponse>> SyncOrders(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::myapp::OrderUpdate, ::myapp::OrderResponse>>(SyncOrdersRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::myapp::OrderUpdate, ::myapp::OrderResponse>> AsyncSyncOrders(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::myapp::OrderUpdate, ::myapp::OrderResponse>>(AsyncSyncOrdersRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::myapp::OrderUpdate, ::myapp::OrderResponse>> PrepareAsyncSyncOrders(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::myapp::OrderUpdate, ::myapp::OrderResponse>>(PrepareAsyncSyncOrdersRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetOrder(::grpc::ClientContext* context, const ::myapp::OrderRequest* request, ::myapp::OrderResponse* response, std::function<void(::grpc::Status)>) override;
      void GetOrder(::grpc::ClientContext* context, const ::myapp::OrderRequest* request, ::myapp::OrderResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void WatchOrderStatus(::grpc::ClientContext* context, const ::myapp::OrderRequest* request, ::grpc::ClientReadReactor< ::myapp::OrderResponse>* reactor) override;
      void BatchUpdateOrder(::grpc::ClientContext* context, ::myapp::Ack* response, ::grpc::ClientWriteReactor< ::myapp::OrderUpdate>* reactor) override;
      void SyncOrders(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::myapp::OrderUpdate,::myapp::OrderResponse>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::myapp::OrderResponse>* AsyncGetOrderRaw(::grpc::ClientContext* context, const ::myapp::OrderRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::myapp::OrderResponse>* PrepareAsyncGetOrderRaw(::grpc::ClientContext* context, const ::myapp::OrderRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::myapp::OrderResponse>* WatchOrderStatusRaw(::grpc::ClientContext* context, const ::myapp::OrderRequest& request) override;
    ::grpc::ClientAsyncReader< ::myapp::OrderResponse>* AsyncWatchOrderStatusRaw(::grpc::ClientContext* context, const ::myapp::OrderRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::myapp::OrderResponse>* PrepareAsyncWatchOrderStatusRaw(::grpc::ClientContext* context, const ::myapp::OrderRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientWriter< ::myapp::OrderUpdate>* BatchUpdateOrderRaw(::grpc::ClientContext* context, ::myapp::Ack* response) override;
    ::grpc::ClientAsyncWriter< ::myapp::OrderUpdate>* AsyncBatchUpdateOrderRaw(::grpc::ClientContext* context, ::myapp::Ack* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::myapp::OrderUpdate>* PrepareAsyncBatchUpdateOrderRaw(::grpc::ClientContext* context, ::myapp::Ack* response, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::myapp::OrderUpdate, ::myapp::OrderResponse>* SyncOrdersRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::myapp::OrderUpdate, ::myapp::OrderResponse>* AsyncSyncOrdersRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::myapp::OrderUpdate, ::myapp::OrderResponse>* PrepareAsyncSyncOrdersRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetOrder_;
    const ::grpc::internal::RpcMethod rpcmethod_WatchOrderStatus_;
    const ::grpc::internal::RpcMethod rpcmethod_BatchUpdateOrder_;
    const ::grpc::internal::RpcMethod rpcmethod_SyncOrders_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 1. Unary — один запрос, один ответ. Самый частый вид RPC,
    //    ведёт себя как обычный вызов функции по сети.
    virtual ::grpc::Status GetOrder(::grpc::ServerContext* context, const ::myapp::OrderRequest* request, ::myapp::OrderResponse* response);
    // 2. Server streaming — один запрос, СЕРВЕР шлёт поток ответов.
    //    Клиент запросил один раз, сервер отдаёт данные порциями
    //    (например, историю статусов заказа).
    virtual ::grpc::Status WatchOrderStatus(::grpc::ServerContext* context, const ::myapp::OrderRequest* request, ::grpc::ServerWriter< ::myapp::OrderResponse>* writer);
    // 3. Client streaming — КЛИЕНТ шлёт поток запросов, сервер отвечает один раз
    //    в конце (например, серия обновлений полей заказа, применяются пачкой).
    virtual ::grpc::Status BatchUpdateOrder(::grpc::ServerContext* context, ::grpc::ServerReader< ::myapp::OrderUpdate>* reader, ::myapp::Ack* response);
    // 4. Bidi (двунаправленный) streaming — оба потока независимы,
    //    клиент и сервер шлют сообщения в любом порядке по одному соединению.
    virtual ::grpc::Status SyncOrders(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::myapp::OrderResponse, ::myapp::OrderUpdate>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetOrder() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOrder(::grpc::ServerContext* /*context*/, const ::myapp::OrderRequest* /*request*/, ::myapp::OrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetOrder(::grpc::ServerContext* context, ::myapp::OrderRequest* request, ::grpc::ServerAsyncResponseWriter< ::myapp::OrderResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_WatchOrderStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_WatchOrderStatus() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_WatchOrderStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WatchOrderStatus(::grpc::ServerContext* /*context*/, const ::myapp::OrderRequest* /*request*/, ::grpc::ServerWriter< ::myapp::OrderResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWatchOrderStatus(::grpc::ServerContext* context, ::myapp::OrderRequest* request, ::grpc::ServerAsyncWriter< ::myapp::OrderResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_BatchUpdateOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_BatchUpdateOrder() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_BatchUpdateOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchUpdateOrder(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::myapp::OrderUpdate>* /*reader*/, ::myapp::Ack* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBatchUpdateOrder(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::myapp::Ack, ::myapp::OrderUpdate>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(2, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SyncOrders : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SyncOrders() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_SyncOrders() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncOrders(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::myapp::OrderResponse, ::myapp::OrderUpdate>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSyncOrders(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::myapp::OrderResponse, ::myapp::OrderUpdate>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(3, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetOrder<WithAsyncMethod_WatchOrderStatus<WithAsyncMethod_BatchUpdateOrder<WithAsyncMethod_SyncOrders<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetOrder() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::myapp::OrderRequest, ::myapp::OrderResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::myapp::OrderRequest* request, ::myapp::OrderResponse* response) { return this->GetOrder(context, request, response); }));}
    void SetMessageAllocatorFor_GetOrder(
        ::grpc::MessageAllocator< ::myapp::OrderRequest, ::myapp::OrderResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::myapp::OrderRequest, ::myapp::OrderResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOrder(::grpc::ServerContext* /*context*/, const ::myapp::OrderRequest* /*request*/, ::myapp::OrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetOrder(
      ::grpc::CallbackServerContext* /*context*/, const ::myapp::OrderRequest* /*request*/, ::myapp::OrderResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_WatchOrderStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_WatchOrderStatus() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::myapp::OrderRequest, ::myapp::OrderResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::myapp::OrderRequest* request) { return this->WatchOrderStatus(context, request); }));
    }
    ~WithCallbackMethod_WatchOrderStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WatchOrderStatus(::grpc::ServerContext* /*context*/, const ::myapp::OrderRequest* /*request*/, ::grpc::ServerWriter< ::myapp::OrderResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::myapp::OrderResponse>* WatchOrderStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::myapp::OrderRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_BatchUpdateOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_BatchUpdateOrder() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackClientStreamingHandler< ::myapp::OrderUpdate, ::myapp::Ack>(
            [this](
                   ::grpc::CallbackServerContext* context, ::myapp::Ack* response) { return this->BatchUpdateOrder(context, response); }));
    }
    ~WithCallbackMethod_BatchUpdateOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchUpdateOrder(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::myapp::OrderUpdate>* /*reader*/, ::myapp::Ack* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::myapp::OrderUpdate>* BatchUpdateOrder(
      ::grpc::CallbackServerContext* /*context*/, ::myapp::Ack* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SyncOrders : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SyncOrders() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackBidiHandler< ::myapp::OrderUpdate, ::myapp::OrderResponse>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->SyncOrders(context); }));
    }
    ~WithCallbackMethod_SyncOrders() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncOrders(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::myapp::OrderResponse, ::myapp::OrderUpdate>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::myapp::OrderUpdate, ::myapp::OrderResponse>* SyncOrders(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_GetOrder<WithCallbackMethod_WatchOrderStatus<WithCallbackMethod_BatchUpdateOrder<WithCallbackMethod_SyncOrders<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetOrder() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOrder(::grpc::ServerContext* /*context*/, const ::myapp::OrderRequest* /*request*/, ::myapp::OrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_WatchOrderStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_WatchOrderStatus() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_WatchOrderStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WatchOrderStatus(::grpc::ServerContext* /*context*/, const ::myapp::OrderRequest* /*request*/, ::grpc::ServerWriter< ::myapp::OrderResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_BatchUpdateOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_BatchUpdateOrder() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_BatchUpdateOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchUpdateOrder(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::myapp::OrderUpdate>* /*reader*/, ::myapp::Ack* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SyncOrders : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SyncOrders() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_SyncOrders() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncOrders(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::myapp::OrderResponse, ::myapp::OrderUpdate>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetOrder() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOrder(::grpc::ServerContext* /*context*/, const ::myapp::OrderRequest* /*request*/, ::myapp::OrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetOrder(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_WatchOrderStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_WatchOrderStatus() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_WatchOrderStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WatchOrderStatus(::grpc::ServerContext* /*context*/, const ::myapp::OrderRequest* /*request*/, ::grpc::ServerWriter< ::myapp::OrderResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWatchOrderStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_BatchUpdateOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_BatchUpdateOrder() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_BatchUpdateOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchUpdateOrder(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::myapp::OrderUpdate>* /*reader*/, ::myapp::Ack* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBatchUpdateOrder(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(2, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SyncOrders : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SyncOrders() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_SyncOrders() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncOrders(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::myapp::OrderResponse, ::myapp::OrderUpdate>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSyncOrders(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(3, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetOrder() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetOrder(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOrder(::grpc::ServerContext* /*context*/, const ::myapp::OrderRequest* /*request*/, ::myapp::OrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetOrder(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_WatchOrderStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_WatchOrderStatus() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->WatchOrderStatus(context, request); }));
    }
    ~WithRawCallbackMethod_WatchOrderStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WatchOrderStatus(::grpc::ServerContext* /*context*/, const ::myapp::OrderRequest* /*request*/, ::grpc::ServerWriter< ::myapp::OrderResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* WatchOrderStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_BatchUpdateOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_BatchUpdateOrder() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->BatchUpdateOrder(context, response); }));
    }
    ~WithRawCallbackMethod_BatchUpdateOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchUpdateOrder(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::myapp::OrderUpdate>* /*reader*/, ::myapp::Ack* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* BatchUpdateOrder(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SyncOrders : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SyncOrders() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->SyncOrders(context); }));
    }
    ~WithRawCallbackMethod_SyncOrders() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncOrders(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::myapp::OrderResponse, ::myapp::OrderUpdate>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* SyncOrders(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetOrder() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::myapp::OrderRequest, ::myapp::OrderResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::myapp::OrderRequest, ::myapp::OrderResponse>* streamer) {
                       return this->StreamedGetOrder(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetOrder(::grpc::ServerContext* /*context*/, const ::myapp::OrderRequest* /*request*/, ::myapp::OrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetOrder(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::myapp::OrderRequest,::myapp::OrderResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetOrder<Service > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_WatchOrderStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_WatchOrderStatus() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::myapp::OrderRequest, ::myapp::OrderResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::myapp::OrderRequest, ::myapp::OrderResponse>* streamer) {
                       return this->StreamedWatchOrderStatus(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_WatchOrderStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status WatchOrderStatus(::grpc::ServerContext* /*context*/, const ::myapp::OrderRequest* /*request*/, ::grpc::ServerWriter< ::myapp::OrderResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedWatchOrderStatus(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::myapp::OrderRequest,::myapp::OrderResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_WatchOrderStatus<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetOrder<WithSplitStreamingMethod_WatchOrderStatus<Service > > StreamedService;
};

}  // namespace myapp


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_order_5fservice_2eproto__INCLUDED
