// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: order_service.proto

#include "order_service.pb.h"
#include "order_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace myapp {

static const char* OrderService_method_names[] = {
  "/myapp.OrderService/GetOrder",
  "/myapp.OrderService/WatchOrderStatus",
  "/myapp.OrderService/BatchUpdateOrder",
  "/myapp.OrderService/SyncOrders",
};

std::unique_ptr< OrderService::Stub> OrderService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< OrderService::Stub> stub(new OrderService::Stub(channel, options));
  return stub;
}

OrderService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetOrder_(OrderService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_WatchOrderStatus_(OrderService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_BatchUpdateOrder_(OrderService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_SyncOrders_(OrderService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status OrderService::Stub::GetOrder(::grpc::ClientContext* context, const ::myapp::OrderRequest& request, ::myapp::OrderResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::myapp::OrderRequest, ::myapp::OrderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetOrder_, context, request, response);
}

void OrderService::Stub::async::GetOrder(::grpc::ClientContext* context, const ::myapp::OrderRequest* request, ::myapp::OrderResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::myapp::OrderRequest, ::myapp::OrderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetOrder_, context, request, response, std::move(f));
}

void OrderService::Stub::async::GetOrder(::grpc::ClientContext* context, const ::myapp::OrderRequest* request, ::myapp::OrderResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetOrder_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::myapp::OrderResponse>* OrderService::Stub::PrepareAsyncGetOrderRaw(::grpc::ClientContext* context, const ::myapp::OrderRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::myapp::OrderResponse, ::myapp::OrderRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetOrder_, context, request);
}

::grpc::ClientAsyncResponseReader< ::myapp::OrderResponse>* OrderService::Stub::AsyncGetOrderRaw(::grpc::ClientContext* context, const ::myapp::OrderRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetOrderRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::myapp::OrderResponse>* OrderService::Stub::WatchOrderStatusRaw(::grpc::ClientContext* context, const ::myapp::OrderRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::myapp::OrderResponse>::Create(channel_.get(), rpcmethod_WatchOrderStatus_, context, request);
}

void OrderService::Stub::async::WatchOrderStatus(::grpc::ClientContext* context, const ::myapp::OrderRequest* request, ::grpc::ClientReadReactor< ::myapp::OrderResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::myapp::OrderResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_WatchOrderStatus_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::myapp::OrderResponse>* OrderService::Stub::AsyncWatchOrderStatusRaw(::grpc::ClientContext* context, const ::myapp::OrderRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::myapp::OrderResponse>::Create(channel_.get(), cq, rpcmethod_WatchOrderStatus_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::myapp::OrderResponse>* OrderService::Stub::PrepareAsyncWatchOrderStatusRaw(::grpc::ClientContext* context, const ::myapp::OrderRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::myapp::OrderResponse>::Create(channel_.get(), cq, rpcmethod_WatchOrderStatus_, context, request, false, nullptr);
}

::grpc::ClientWriter< ::myapp::OrderUpdate>* OrderService::Stub::BatchUpdateOrderRaw(::grpc::ClientContext* context, ::myapp::Ack* response) {
  return ::grpc::internal::ClientWriterFactory< ::myapp::OrderUpdate>::Create(channel_.get(), rpcmethod_BatchUpdateOrder_, context, response);
}

void OrderService::Stub::async::BatchUpdateOrder(::grpc::ClientContext* context, ::myapp::Ack* response, ::grpc::ClientWriteReactor< ::myapp::OrderUpdate>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::myapp::OrderUpdate>::Create(stub_->channel_.get(), stub_->rpcmethod_BatchUpdateOrder_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::myapp::OrderUpdate>* OrderService::Stub::AsyncBatchUpdateOrderRaw(::grpc::ClientContext* context, ::myapp::Ack* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::myapp::OrderUpdate>::Create(channel_.get(), cq, rpcmethod_BatchUpdateOrder_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::myapp::OrderUpdate>* OrderService::Stub::PrepareAsyncBatchUpdateOrderRaw(::grpc::ClientContext* context, ::myapp::Ack* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::myapp::OrderUpdate>::Create(channel_.get(), cq, rpcmethod_BatchUpdateOrder_, context, response, false, nullptr);
}

::grpc::ClientReaderWriter< ::myapp::OrderUpdate, ::myapp::OrderResponse>* OrderService::Stub::SyncOrdersRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::myapp::OrderUpdate, ::myapp::OrderResponse>::Create(channel_.get(), rpcmethod_SyncOrders_, context);
}

void OrderService::Stub::async::SyncOrders(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::myapp::OrderUpdate,::myapp::OrderResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::myapp::OrderUpdate,::myapp::OrderResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_SyncOrders_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::myapp::OrderUpdate, ::myapp::OrderResponse>* OrderService::Stub::AsyncSyncOrdersRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::myapp::OrderUpdate, ::myapp::OrderResponse>::Create(channel_.get(), cq, rpcmethod_SyncOrders_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::myapp::OrderUpdate, ::myapp::OrderResponse>* OrderService::Stub::PrepareAsyncSyncOrdersRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::myapp::OrderUpdate, ::myapp::OrderResponse>::Create(channel_.get(), cq, rpcmethod_SyncOrders_, context, false, nullptr);
}

OrderService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrderService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrderService::Service, ::myapp::OrderRequest, ::myapp::OrderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OrderService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::myapp::OrderRequest* req,
             ::myapp::OrderResponse* resp) {
               return service->GetOrder(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrderService_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< OrderService::Service, ::myapp::OrderRequest, ::myapp::OrderResponse>(
          [](OrderService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::myapp::OrderRequest* req,
             ::grpc::ServerWriter<::myapp::OrderResponse>* writer) {
               return service->WatchOrderStatus(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrderService_method_names[2],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< OrderService::Service, ::myapp::OrderUpdate, ::myapp::Ack>(
          [](OrderService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::myapp::OrderUpdate>* reader,
             ::myapp::Ack* resp) {
               return service->BatchUpdateOrder(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrderService_method_names[3],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< OrderService::Service, ::myapp::OrderUpdate, ::myapp::OrderResponse>(
          [](OrderService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::myapp::OrderResponse,
             ::myapp::OrderUpdate>* stream) {
               return service->SyncOrders(ctx, stream);
             }, this)));
}

OrderService::Service::~Service() {
}

::grpc::Status OrderService::Service::GetOrder(::grpc::ServerContext* context, const ::myapp::OrderRequest* request, ::myapp::OrderResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OrderService::Service::WatchOrderStatus(::grpc::ServerContext* context, const ::myapp::OrderRequest* request, ::grpc::ServerWriter< ::myapp::OrderResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OrderService::Service::BatchUpdateOrder(::grpc::ServerContext* context, ::grpc::ServerReader< ::myapp::OrderUpdate>* reader, ::myapp::Ack* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OrderService::Service::SyncOrders(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::myapp::OrderResponse, ::myapp::OrderUpdate>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace myapp
#include <grpcpp/ports_undef.inc>

